### ISSUE TITLE
Inline edit user contributed record.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#1]
At present the edit interface for an individual record in a user created layer is very limited and awkward, especially for the description which should have a larger text field. The way it tries to work is to make a cell in the table editable. This is too crowded. It would be better if it opened up in a pop up div form, giving adequate room and maybe a scroll for editing each field. Once this is done consider also:
- Make the description field formatible, but only with a limited set of format choices to avoid user's bad design choices or abuses. Eg: limit to bold, italic, h1, h2, h3, bullets and links. No colours.
- Add a map picker for the coordinates. There is a good one to be obtained from another of our projects.
- Use the date picker that is used in other components (this handles allowing any kind of date that might be used in humanities, not just the usual restricted ones)

**Comment by IanMcCrabb** [comment]
Figure we need to assign a priority to this.

**Comment by HughCraig** [comment]
I think we have done this but it would be good to check if all this functionality exists.
