### ISSUE TITLE
Filters apply to gazetteer search but not to cultural layers

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#108]
Filters apply to gazetteer search but not to layers. Eg: if you search Newcastle and filter by State NSW, it limits gazetteer results to NSW, but includes anything from the Culture Layers from anywhere.

**Comment by yangli0516** [comment]
This is due to that orWhere clauses are not grouped correctly. Have fixed this for other conditions such as shapes as well. Please have a detailed test to see whether it breaks anything.

**Comment by HughCraig** [comment]
I tested various placenames with a state nominated in the filter and gazetteer and layers checked and unchecked and got results as expected.
