### ISSUE TITLE
Migrations look out-of-date

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/GHAP#11]
The migrations defined in Laravel seem to be out-of-date and doesn't matching the current database schema. For example, table 'dataset_dataitem' doesn't exit in the current schema. And most of fields from table 'dataset' are not defined in the migration.

@BillPascoe Just to clarify whether these database migrations are abandoned, and the database schema is directory defined in the database. I'm trying to create new tables for the multilayers, do I make the change directly in the database and do SQL dumps after or create migrations for the new tables?

**Comment by BillPascoe** [comment]
The migrations are abandoned. You could either just create tables in postgres database, and create the matching laravel code manually, or do some work to get migrations working.

**Comment by IanMcCrabb** [comment]
Will leave this with Hugh to prioritize.
