### ISSUE TITLE
Wording after user sign up

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#113]
When a user is signing up, after they enter their details for the first time it says:
"Before proceeding, please check your email for a verification link. If you did not receive the email, click here to request another."
Change this to say:
"Please check your email for a verification link. Allow a few minutes for it to arrive and check your spam or clutter folder. If you did not receive the email, click here to request another."

**Comment by HughCraig** [comment]
Good to tidy this up.

**Comment by yangli0516** [comment]
Resolved

**Comment by HughCraig** [comment]
Assuming this is OK!
