### ISSUE TITLE
Download as CSV not working

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#120]
I completed a search in GHAP then tried to download it. The GeoJSON and KML options worked as expected but with the CSV option I got this error message:

<html>
<body>

Call to undefined method Symfony\Component\HttpFoundation\StreamedResponse::header()
--
in Cors.php line 19

</body>
</html>

**Comment by yangli0516** [comment]
Fixed.

**Comment by HughCraig** [comment]
Thanks! Works as expected now.
