### ISSUE TITLE
Temporal Earth view of place not working

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#122]
If I look at some individual search results and click on 'View Place In' and then choose Temporal Earth, no map view opens. The other three options, 3D Viewer, Google Maps and Trove Search all produce the expected result.

We have deprecated the Temporal Earth view in Multilayer on the grounds that we are not supporting future development with Temporal Earth so maybe we should choose not to include the Temporal Earth option in 'View Place In'.

**Comment by IanMcCrabb** [comment]
As discussed, Yang to remove functionality in GHAP Beta through configuration

**Comment by yangli0516** [comment]
Have disabled the temporal earth in the testing site.
