### ISSUE TITLE
Download in Advanced Search

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#123]
The Advanced Search window includes a check box for 'Download'. Checking this does not seem to produce any different result from leaving it unchecked.

**Comment by IanMcCrabb** [comment]
Remove feature for GHAP Beta

**Comment by yangli0516** [comment]
Had a second look, the download check box will work if you choose a format from the select list above. Maybe we still keep this feature? Validation could be added upon the search to notify the user the format is not selected when the download option is checked.

**Comment by BillPascoe** [comment]
Just make it download as CSV by default, if no format is selected.

**Comment by HughCraig** [comment]
Worth doing given this seems like a small-scale task.
