### ISSUE TITLE
Link to individual site in 3D view displays wrong

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#124]
If I click the link to view an individual site from the user edit layer (button to the left of the individual record, not the layer)
it goes to a URL like this, which is handled in a special way by the viewer, which is to display whatever is passed in the GET parameters:
https://tlcmap.org/3d/place.html?latlng=-32.41447601,151.06484413&id=9973&title=Ravensworth+Homestead&placename=&description=Ravensworth+Homestead.+Colonial+building.+Important+to+Wonnarua+history%2C+including+campaigns+in+the+frontier+wars.+Desired+by+Glencore+coal+mining.+See%0Ahttps%3A%2F%2Fhunterlivinghistories.com%2F2018%2F06%2F20%2Faerial-photos-ravensworth%2F%0Aand+https%3A%2F%2Fwww.facebook.com%2FDavidShoebridgeMLC%2Fposts%2F372937980859744%0Ahttps%3A%2F%2Fwww.smh.com.au%2Fnational%2Fnsw%2Fhallowed-ground-outcry-over-plan-to-remove-homestead-for-coal-mine-20210417-p57k14.html%0A%28date+is+not+accurate%2C+SMH+says+%27dates+from+the+1820s%29&linkback=https://tlcmap.org/ghap/myprofile/mydatasets/113

This doesn't display the information correctly in the description box. It is also different to another way of getting the information, which is by passing in the JSON URL as a get parameter as follows. The above problem should be fixed by replacing it with a URL like the following. This is the URL in the links from an individual record in the public facing page (from search or navigated to through layer). However, this also has a problem in that it only displays the TLCMap log, and not any other information, such as a title, description, warning and link back to the layer. So that needs fixing too.

https://tlcmap.org/view/3d.html?load=https%3A%2F%2Ftlcmap.org%2Fghap%2Fsearch%3Fid%3Dt26f5%26format%3Djson

**Comment by yangli0516** [comment]
Have changed the URL to use the 3d viewer for places in public layers, user layers and search results. The places metadata are displayed in the popup instead of the info block. That 's kind of the default behavior of the 3D viewer, as it's loading a feature collection only has a single feature.

**Comment by HughCraig** [comment]
URL looks right now for these records.
