### ISSUE TITLE
Error in JSON breaking Moravian Mission Layer

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#126]
Moravian Missions layer won't display. Attempt to look at the JSON export creates error.
Investigate cause and handle gracefully with error message or applying defaults etc.

Layer: https://www.tlcmap.org/ghap/publicdatasets/135
Map: https://www.tlcmap.org/view/3d.html?load=https://www.tlcmap.org/ghap/publicdatasets/135/json
JSON feed: https://www.tlcmap.org/ghap/publicdatasets/135/json

**Comment by yangli0516** [comment]
This may be caused by some place with empty geo locations. Have added the checks upon the JSON generation function.

**Comment by HughCraig** [comment]
It seems that if Issue 157 is solved this layer will display OK.
