### ISSUE TITLE
Extend time out for account emails

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#130]
Extend time out for confirm email when signing up, and for password change to 72 hours. 
These emails tend to be caught by institutional spam traps. Normally they just end up in the spam/junk folder where the user can find them, but sometimes the institution only sends the user a blocked email report the following day, so the user can't release the email and act on it till this next day.
The information when such emails are sent should add, "Check your spam or junk folder for blocked emails from access@tlcmap.org. Sometimes your institution may not release a blocked email report till the next day. You may need to whitelist access@tlcmap.org."

**Comment by BillPascoe** [comment]
If this is a small tweak, can we do it in Live as well?

**Comment by yangli0516** [comment]
Have made these settings as variables in the .env file that one can easily change the expire time.
