### ISSUE TITLE
MultiLayer - Colours

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#138]
Dear All,
How about this: 
1.	Colours are allotted to layers in a standard order, i.e.
1-dark yellow
2-light blue
3-green
4-light yellow
5-dark blue
6-red
7-purple
Etc
2.	Thus to assign particular colours to particular layers, layers should be added in the ‘right’ order. To skip colours, add a dummy layer and then hide it once the multilayer is created, by clicking on it in the list in the legend to the left of the screen. 
Best wishes, 
Hugh.

I hope you’re well – really looking forward to the workshop in a couple of weeks (and I ran into Matthew Martin this afternoon who is also humming along with his talk). I’ve had a crack at putting up my work on morocco leather as a multilayer, so that I can show different colours of morocco leather bookbindings geocoded by the people who owned them – you can see the first results here: https://www.tlcmap.org/view/collection-timeline.html?load=https://www.tlcmap.org/ghap/publiccollections/12/json – but I would really like to be able to choose what colours the different layers appear in, so that they correspond with the binding colours (yellow, red, black, brown, green, blue and perhaps grey for unlisted) – is this possible? No rush to answer this – or at all if you’re too busy!

**Comment by BillPascoe** [comment]
Would have been sorted by the new customisation features.
