### ISSUE TITLE
Timeline view initial zoom level is not correct for some layers with a large amount of dataitems

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/GHAP#139]
For example, the AusStage venues:

https://test-ghap.tlcmap.org/publicdatasets/232

Once the timeline is loaded, you will get a white screen in the map area. Need to drag and zoom the map area to view the map properly.

This also happens for multilayers:

https://test-ghap.tlcmap.org/publiccollections/13

**Comment by yangli0516** [comment]
It looks like some AusStage entries have the wrong lat and long values, which causes the timeline view map out of the focus. Some places have the actually longitude in the latitude column (which exceeds the range of -90 to 90) and have the latitude value in the longitude column.

**Comment by yangli0516** [comment]
Have fixed the data, and now the timeline view is working OK.

**Comment by IanMcCrabb** [comment]
OK
