### ISSUE TITLE
Guides page causes confusion by going to a different domain

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#145]
Perhaps revisit link to and from GHAP to TLCMap

I did not notice the domain had changed after going to the page. After exploring a bit under tools and examples, I found the content to be irrelevant to GHAP. Maybe put the page under the GHAP domain and add a link to the TLC map resource page.  The guide itself is well-structured and easy to follow though.

**Comment by IanMcCrabb** [comment]
Isobel to come up with UI design solution

**Comment by BillPascoe** [comment]
It's all under tlcmap.org domain. Only the server name ghap changes, and that's not so strange these days.
The whole point was to make GHAP and TLCMap, incl guides seperate.
