### ISSUE TITLE
Search result UI - Search result not formatting well 

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#152]
Search a place name and looking at the displayed results | The results are not always aligned (column-wise); they are too much space on the left and right sides on browser (looks good on mobile browser though); adding link-breakers could make the resulting entries easier to read.

**Comment by yangli0516** [comment]
Have added the zebra effect to the result list.

**Comment by yangli0516** [comment]
In terms of the column alignment, we could add the empty column for results which have less than 5 columns, and make each column with equal width. However, some column may have wider non-breakable content such as long URLs. We may need to force break these contents into multiple lines.

Also can we make the search result container the same width as the header to make it a little bit wider?

**Comment by IanMcCrabb** [comment]
Indeed, an empty column to ensure that columns are of equal width and extend the container as per the browse layers table.

**Comment by yangli0516** [comment]
Resolved

**Comment by IanMcCrabb** [comment]
Hugh, if you might test and close if OK.

**Comment by HughCraig** [comment]
Looks orderly and easy to read now.
