### ISSUE TITLE
Search result UI - Click the blue-text name of a search result entry and navigates to a new page | The new 

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#153]
Clicking a search result entry links to itself page is showing exactly the same information before the click of the displaying place, which is not very useful. If the link is directing to some new page such as a metadata/ description page (like the layer link for the entry), maybe just make it unclickable.

**Comment by BillPascoe** [comment]
The purpose is to link to a unique entry for this place with it's own URL that is not within the layer, so this is not a problem.
Each place should have it's own URL and own page.
