### ISSUE TITLE
CORS errors

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#156]
The search in Quick Coordinates is not working. https://www.tlcmap.org/quicktools/quickcoordinates.html
(if you enter in a search at the bottom it should call ghap and show purple dots on the map) 
Looking at the javascript console it is reporting CORS errors. Please check and correct any CORS issues with GHAP.

**Comment by yangli0516** [comment]
The CORS middleware has been already applied to the search page from a previous commit. However, it's only available in the current testing site. Can we suspend this issue until the next release of GHAP. There would be works on the Quick Coordinates tool itself to adapt the new GHAP url.

**Comment by BillPascoe** [comment]
This is a very noticeable problem in workshops so is a high priority, but if next release of GHAP is within a month or so, we can leave it till then.

**Comment by IanMcCrabb** [comment]
@HughCraig will leave this with you to assign to us

**Comment by yangli0516** [comment]
@BillPascoe , just wondering if you are planning to set up a repository for quick coordinates as this issue might related to changes on code from quick coordinates.

**Comment by yangli0516** [comment]
Test site updated.

**Comment by MufengNiu** [comment]
@BillPascoe: For the Quick Coordinates codebase, in the file map.init.js at line 242, 
the URL is currently set as "https://tlcmap.org/ghap/search?"+selectVal+"="+input+"&format=json".
Please update it to "https://ghap.tlcmap.org/search?"+selectVal+"="+input+"&format=json" to avoid the CORS header lost issue.

**Comment by BillPascoe** [comment]
Thanks for finding that simple fix. Please make the change directly on the server. Quick Coordinates is not a complicated system with user data, so ok to make a quick back up copy of the file you are editing and edit it (assuming you know 'vi' or other way to edit direct on server). I have created a repo for QuickCoordinates and invited Yang and Mufeng. There is nothing in it at the moment, but I'll make another task to get the production code and commit it.

**Comment by MufengNiu** [comment]
Update: Please note that we have set a maximum page limit of 5000 on GHAP, The search will fail if the results exceed this limit.

**Comment by IanMcCrabb** [comment]
@yangli0516 as Bill is on leave I figure we can just move this to deploy.
