### ISSUE TITLE
Integrate with TSherrats Trove Maps GLAM Workbench stuff

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#160]
Tim Sherrat's GLAM workbench has some cool new tools.
One thing is just import the csv of coordinates from map metadata as a GHAP layer.
Also, see how else to work with this.

Bill,

Just letting you know that I've updated the Trove maps section of the GLAM Workbench. In my latest harvest of metadata about Trove's digitised maps I've pulled in coordinates that aren't in the API data, but can be scraped from the work pages. I've managed to parse most of the coordinate strings and used them to create a few demo maps of maps. I've also shared the datasets with the metadata and parsed coordinates. Thought it might be of use to you.

[https://glam-workbench.net/trove-maps/](https://protect-au.mimecast.com/s/5SP8CWLJMvFjjmELys6_Dd1?domain=glam-workbench.net)

Cheers, Tim

----
Tim Sherratt ([tim@timsherratt.org](mailto:tim@timsherratt.org))
[timsherratt.org](https://protect-au.mimecast.com/s/S2TkCXLKNwFnnoQPMcV09Z9?domain=timsherratt.org)
@wragge on Twitter
GLAM Workbench: [https://glam-workbench.net/](https://protect-au.mimecast.com/s/upd7CYWLOxh3327W6C9OdXQ?domain=glam-workbench.net)

The GLAM Workbench & related projects receive no direct funding. If you'd like to support this work you can...
Sponsor me on GitHub: https://github.com/sponsors/wragge
Buy me a coffee: [https://www.buymeacoffee.com/wragge](https://protect-au.mimecast.com/s/4o_3CZYMPyCMM96qotyD4uG?domain=buymeacoffee.com)

**Comment by wragge** [comment]
The datasets are currently split -- one with all the bibliographic metadata, the other with limited metadata and the parsed coordinates. Would you like a version that has all the metadata and the parsed coords?

**Comment by IanMcCrabb** [comment]
Present quite an opportunity to showcase integration of TLCMap with Trove data implementation of a Jupyter Notebook.  Would be a good exemplar in front of ARDC and take advantage of the recent enhancements in the TLCMap Views framework…   

@Mufeng Yang and I can brief you on getting a basic Notebook up and going. but would need to go back to Hugh/Bill to refine the research use case…

**Comment by BillPascoe** [comment]
Producing Jupyter Notebooks to demo TLCMap GHAP API is already being done by Kaine on ARDC budget. Don't work on this. I'll assign this to Kaine. The notebooks will be complete in a week or two.

**Comment by BillPascoe** [comment]
Sorry I misunderstood this and thought it was about creating Jupyter notebooks that Kaine was already doing. Actually it's about working with Tim Sherrat's Trove stuff. We still need a clearer task description.

**Comment by IanMcCrabb** [comment]
https://glam-workbench.net/trove-maps/
-provides access to 2 Notebooks:
Exploring-digitised-maps.ipynb
-this one harvests and analyses metadata about maps...
parse_coordinates.ipynb
-this one looks really interesting for us as it parses and coverts coordinate strings (including bounding boxes to centroids).  We can start by feeding the dataset to TLCMap views and then think about what metadata to expose in popups and also potentially get user interaction from clicking pin to layer the map image over our basemap as Tim has done.

We can try this out and contribute the result back to Tim for inclusion on GLAM Workbench if he sees value in it.  

We could also package a companion Notebook to generate the data set in a format ready for immediate upload as layer GHAP.

**Comment by MufengNiu** [comment]
@BillPascoe ,Propose that as the first step we duplicate Tim's notebook and just implement TLCmaps to prove the concept on embedding TLCmap views in Jupyter notebooks. Anticipated just a couples of hours work.

**Comment by IanMcCrabb** [comment]
@MufengNiu can you add a link to the Jupyter Notebook .

**Comment by IanMcCrabb** [comment]
@MufengNiu if you could add the link to the Notebook, I'd like to have another look at this.

**Comment by MufengNiu** [comment]
@IanMcCrabb https://colab.research.google.com/drive/1scutWstH2C_GtTJMSs3Hic-GAl3B4K2Q?usp=sharing

**Comment by IanMcCrabb** [comment]
Thanks @MufengNiu

**Comment by IanMcCrabb** [comment]
@BillPascoe  and @HughCraig We took this one on as an experiment ourselves rather than as a TLCMap issue, so will manage this as Systemik initiative...
