### ISSUE TITLE
Check boxes for search

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#166]
When I go to https://test-ghap.tlcmap.org/ I see two check boxes for the simple search -- GHAP and ANPS. I was expecting three check boxes, ANPS, NCG, and Layers. Thus the user could search all three or any one or any combination of two. I might, for instance, want to search NCG because it comes from GeoScience Australia, is recent, etc.

**Comment by IanMcCrabb** [comment]
Yang has not yet loaded the NCG data as we wanted to do the testing of the db changes and code refactor based on the existing data.  Once testing is done it will only take a day to upload the NCG data set (Yang has prepped the process).  Checkbox will them appear automatically..,
