### ISSUE TITLE
Multiple feature terms for the same feature

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#169]
If I start to type "mountain" in the feature term box I get
Mountain Peak
Mountain
Mountains
mountain range
mountains
mountain
This reflects (a) the fact that ANPS has multiple terms for the same feature with a mixture of upper and lower case and (b) the fact that NCG has its own feature term system which though internally consistent and always lower case does not always match up with the ANPS terminology. Would it be possible (and worth the effort) to allow users to search in GHAP for multiple terms, maybe copied somehow from those suggested by the auto-completion process? Otherwise we maybe need to highlight this aspect -- multiple terms in our combined gazetteer for the same feature -- in documentation, added to the nicely set out guide to Advanced Search already on the GHAP site..
Another example is "railway station" -- as you type you get
Railway Station
rail station
railway station
light rail station
Incidentally, with all sources ticked, you get 3730 hits for Railway Station, 3398 hits for rail station, 4262 hits for railway station, and 8 hits for light rail station.

**Comment by IanMcCrabb** [comment]
capability to select multiple terms seems to make sense

**Comment by yangli0516** [comment]
Test site updated
