### ISSUE TITLE
RO-Crate - 'provenance'

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#173]
This is looking very good. I was wondering how we could add the information that it was downloaded from TLCMap GHAP.
Looking at the ROCrate specification, under 'provenance', I see you can describe the equipment or application used to process files, or the repository it was downloaded from.
https://www.researchobject.org/ro-crate/1.1/provenance.html#software-used-to-create-files 

TLCMap isn't an official repository, so should be understood as a web application. From the website it looks like we need to have an entry in the JSON like this (unfortunately we don't have rigorous versioning set up). JSON-LD still confuses me a little bit, so I could be wrong, and if you think there is a better way, please go ahead.

This should should also be added to the HTML. Then we can ask Peter Sefton to check.

{
      "@id": "https://ghap.tlcmap.org/",
      "@type": "SoftwareApplication",
      "url": "https://ghap.tlcmap.org/",
      "name": "TLCMap Gazetteer of Historical Australian Places",
      "version": "GHAP 3.0"
}

and then reference this from each of the file's metadata (or possibly just the whole layer/multilayer?? If not sure, just do one, and we'll ask Peter Sefton and give him an example).

"instrument": {
        "@id": "https://www.imagemagick.org/"
      },
...
        {
            "@id": "TLCMLayer_112.csv",
            "@type": "File",
            "name": "CSV export of Aboriginal Port Stephens (1826)",
            "description": "CSV export of the layer data",
            "encodingFormat": "text\/csv",
                  "instrument": {
                        "@id": "https://ghap.tlcmap.org/"
                   }
        },

**Comment by BillPascoe** [comment]
One last clarification is being sought from Peter Sefton on this particular point. I'll leave it open and put the other ROCrate tasks in another job.

**Comment by BillPascoe** [comment]
Peter has advised no problem with the instrument provenance section.
