### ISSUE TITLE
Date Edit Widget

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#175]
Add date edit widget to create and edit place form. This should be the TLCMap developed date editor (ask Bill for the code) that enables any date to be picked from the calendar and or edited manually, and has none of the limitations common in other systems (eg: allow year only, dd-mm-yyyy, negative year, any number of digits in the year, etc, ie: any data can be made compatible with the ISO standard).
This should follow issue #30

**Comment by yangli0516** [comment]
As the widget has already been applied to the start/end dates for layers, multilayers, and places, should we close this issue?
