### ISSUE TITLE
WYSIWYG Widget

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#176]
Add WYSIWYG editor for textarea fields in create and edit place form. Limit available edit options to heading level, italics, bold, add link, bullets. Nothing else.
This should follow issue #30

**Comment by BillPascoe** [comment]
The fields to apply limited WYSIWYG editor are as follows. It makes sense to add the WYSIWYG editor to some of the layer and multilayer metadata fields while doing this:

For each place record:
- Description
- Source

For Layer and Multilayer:
- Description
- Content Warning
- Citation
- Usage Rights (note that layer says 'Rights' but Multilayer says 'Usage Rights' - make them both 'Usage Rights')

**Comment by yangli0516** [comment]
Implemented the editor, and left a note about preventing XSS attacks in the README.md.

**Comment by BillPascoe** [comment]
All of it works except adding a hyperlink. If I select a word, or don't select a word, and click the hyperlink icon it pops up with the form to enter the link details, but I cannot click into and edit the URL, Text To Display, and Title fields.

**Comment by yangli0516** [comment]
Fixed.

This is an issue related to TinyMCE displaying in Bootstrap modals. 

https://github.com/tinymce/tinymce/issues/782

**Comment by BillPascoe** [comment]
Done. Works great.
