### ISSUE TITLE
Delete place confirmation

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#177]
Add 'Are you sure you want to delete?' confirmation to the 'delete' button for each place listed in the layer editor.

**Comment by MufengNiu** [comment]
Seems like we already have this feature. 
![SAMPLE](https://github.com/HughCraig/GHAP/assets/51284623/52d0d049-c3de-49d7-a40b-be24b7f8c528)

**Comment by BillPascoe** [comment]
As commented this is already implemented.
