### ISSUE TITLE
TLCMap site does not come on first page in Google search

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#179]
If you google 'TLCMap' the site does not appear on the first page of hits. The site used to be first on the page. This may be because of our change to WordPress. Is there some SEO we can do to change this?
(BTW If you google 'GHAP' you get God Has A Plan etc, as this is a common and ambiguous acronym. 'Gazetteer of Historical Australian Places' comes second on the page.)

**Comment by BillPascoe** [comment]
I looked at the source HTML for our homepage and it has the metatag:
<meta name='robots' content='noindex, nofollow' />
Which stops it being indexed by search engines. This should be removed asap.

**Comment by BillPascoe** [comment]
There was a setting in Wordpress for discouraging search indexing which was ticked. I unticked it and that removed this metatag. We may need to wait a month for the spiders to crawl around again.

**Comment by IanMcCrabb** [comment]
@isobel-andrews if you could have a look at this as soon as you can.

**Comment by BillPascoe** [comment]
I already fixed the underlying problem, but it would be worth looking into whether we can coax Google into re-indexing sooner rather than later. (also btw, while I was there, I added a logo that will appear in the browser tab, instead of the wordpress logo)

**Comment by isobel-andrews** [comment]
I just googled 'tlc map' and our site came up as the first result, so it looks like Google has resolved it!
