### ISSUE TITLE
SendGrid

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#180]
I've generated a new key. But to get them to reactivate it, I will need to sent them a root cause analysis. Are you able to give me any information for the #TBA sections below?
I'm not putting in a GitHub issue, in case we put anything in there that causes them alarm. They seem to monitor GitHub.

I can't think of anything at my end that might have caused the breach. Perhaps because of a change in Uni Melbourne policy, last week Microsoft slurped all my documents folder into the cloud and deleted the local copy. I spent a lot of time downloading it all again. But I'm sure the API wasn't recorded in that anyway.

Incident Description
What happened?
I appears our key was being used to send phishing emails from the address [access@tlcmap.org](mailto:access@tlcmap.org) which we use for account creation and password reset confirmation emails.

What exact dates did the fraudulent activity start and end? 
According to the message from SendGrid it started on 2023-05-01 and ended on 2023-05-03.

When did you discover it?
When SendGrid sent us an account suspension notice.

Root Cause  
How did it happen?

# TBA

Resolution  
What measures have you taken to fix the problem?
API Key deleted immediately and a new one created.

Corrective / Preventive Actions
What measures have you taken to stop the activity and prevent it in the future?

# TBA

Kind regards,
Bill Pascoe

**Comment by IanMcCrabb** [comment]
@BillPascoe Yang is travelling today so wont be able to respond until tomorrow at the  earliest.

**Comment by BillPascoe** [comment]
Ok thanks for letting me know. We'll have to be patient.

**Comment by IanMcCrabb** [comment]
The cause of this breach seems to be that the testing site is opened for debug. The key is likely exposed through the debug error message when there're errors during the email sending process.

The testing site was protected by the simple authentication before and only open to trusted users, and it was OK to leave the debug mode on as it can facilitate the debugging when there's something wrong. However, at one stage we've decided to open the testing site to a wider audiences, and the viewer won't work properly when the simple authentication was in place. We simply removed the layer of simple authentication, but neglected to close the debug mode.

I have disabled the debug mode for the testing site, and replaced the keys in production and testing sites with the one you sent earlier. Please let me know if you need anything else.

**Comment by BillPascoe** [comment]
Report provided to sendgrid and account has been reactivated. Tested password reset and email arrives.
Seems good.
