### ISSUE TITLE
Change Layers Menu

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#183]
Once you have moved away from the GHAP front page it's not obvious how to get back to search. The only way is to click the logo which takes you to the home page. Improve this by:
- Remove 'Browse' from the menu item 'Browse Layers' so it just says 'Layers'
- Add 'Search' to the 'Layers' menu (linking back to the main search page), so it contains three items: Search, Layers, Multilayers
This is a trivial task. Put it in the next update.

**Comment by IanMcCrabb** [comment]
@BillPascoe alternative might be to move 'About' under the Help menu and use that space for Search.

**Comment by BillPascoe** [comment]
Maybe we let Isobel decide.

**Comment by IanMcCrabb** [comment]
@isobel-andrews  if you might review.
