### ISSUE TITLE
ROCrate Review

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#186]
Peter Sefton responded to our request to review an example of our ROCrate code. We cannot do all that he suggested as we aren't enforcing or encouraging some things yet, and are just filling the field with user input. That's ok though. I had one more question for him on the provenance 'instrument' section which is in job #173 
Here are the changes we should make:

1.
"datePublished": "2023-05-03",

this is the date downloaded. It should be the date it was uploaded to TLCMap.

2.
"inLanguage" attribute should be "language"

3. 
The license should reference a section with more details, as in the example on this page: https://www.researchobject.org/ro-crate/1.0/

"license": {
    "@id": "https://creativecommons.org/licenses/by/4.0/"
  },

{
  "@id": "https://creativecommons.org/licenses/by/4.0/",
  "@type": "CreativeWork",
  "name": "CC BY 4.0",
  "description": "Creative Commons Attribution 4.0 International License"
},

However, we are not yet enforcing or encouraging people to use standard licences in this way. So for now it should just be a reference internal to this rocrate file, like the following. We should start using this structure now though, so we can expand it in future to reference externally defined licences where possible:
"license": {
    "@id": "?????????????????"
  },
{
  "@id": "???????????????",
  "@type": "CreativeWork",
  "name": "CC BY 4.0 - or whatever the person entered into this field"
},

**Comment by BillPascoe** [comment]
Peter has advised there is no problem with the instrument provenance section. So go ahead just with the above changes.

**Comment by yangli0516** [comment]
Have applied the changes.

**Comment by BillPascoe** [comment]
Just one more thing. I realised I should do the obvious test, and open a TLCMap ROCrate in Describo. Describo reports one error in the ID of Create Actions. The error message points to this article for guidance: 
https://github.com/describo/crate-builder-component/blob/master/README.identifiers.md

It seems that the ID should start with '#' to indicate the reference is internal to the crate.
Ie: an id generated as "9dfba370-7bec-4fd6-b002-73f838cac6fe" should prepend prefix to be "#9dfba370-7bec-4fd6-b002-73f838cac6fe"

eg:
...
{
            "@id": "#9dfba370-7bec-4fd6-b002-73f838cac6fe",
            "@type": "CreateAction",
            "instrument": {
...

**Comment by yangli0516** [comment]
> Just one more thing. I realised I should do the obvious test, and open a TLCMap ROCrate in Describo. Describo reports one error in the ID of Create Actions. The error message points to this article for guidance: https://github.com/describo/crate-builder-component/blob/master/README.identifiers.md
> 
> It seems that the ID should start with '#' to indicate the reference is internal to the crate. Ie: an id generated as "9dfba370-7bec-4fd6-b002-73f838cac6fe" should prepend prefix to be "#9dfba370-7bec-4fd6-b002-73f838cac6fe"
> 
> eg: ... { "@id": "#9dfba370-7bec-4fd6-b002-73f838cac6fe", "@type": "CreateAction", "instrument": { ...

Fixed.
