### ISSUE TITLE
Refactor - legacy tinymce and wysiwyger.js

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#187]
It looks like in the past I attempted to add wysiwyg editor to GHAP and could not finish in time and so commented it out.
However, there are still script references to tinymce.min.js and wysiwyger.js
These are probably redundant junk that should be removed.
Check they are not actually used and remove them to clean up code. Especially to avoid confusion with the new wysiwyg features.

**Comment by IanMcCrabb** [comment]
Presume we can  close this
