### ISSUE TITLE
Editing a place changes order

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#188]
If I edit a place through the GHAP interface, it goes to the end of the list of places, and the order is changes. Preserving the order of places as uploaded is important for journey visualisations that don't have dates.
Find a way to retain the order of places as uploaded or added.
Later we may also add a feature to allow user to change the order of places in the app, but this is a lower priority. Because of this though, it may be easiest to simply create a 'sortorder' column, and automatically increment it for uploaded records, or user added records, then in output it can be sorted by this column (you could still order by date for date based journeys if needed, etc).

**Comment by MufengNiu** [comment]
1. "If I edit a place through the GHAP interface, it goes to the end of the list of places, and the order is changes" . Testing whether id is changed or the order is changed after a place is edited.
2. "Preserving the order of places as uploaded is important for journey visualizations that don't have dates."  Find a way to preserve the order of places in journey visualisations without dates.

**Comment by yangli0516** [comment]
@MufengNiu , could you document here about where and what orders you changed.

e.g. 

- In a layer page (`/publicdatasets/{id}`, have set the order of places explicitly by their IDs. 
- ...

**Comment by MufengNiu** [comment]
The following changes has been made:

- On the public layer page (`/publicdatasets/{id}`), have explicitly set the order of places by their IDs.
- On the private layer page (`/myprofile/mydatasets/{id}`),have explicitly set the order of places by their IDs.
- For the data feed (both viewing and download) on the private layer page (`/myprofile/mydatasets/{id}/kml/json/csv`), have set the order of places explicitly by their IDs.
- Similarly, for the data feed (both viewing and download) on the public layer page (`/publicdatasets/{id}/kml/json/csv`), have set the order of places explicitly by their IDs.

**Comment by yangli0516** [comment]
Test site has been updated.
