### ISSUE TITLE
Autofill suggest in edit fields for Feature Term and LGA

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#189]
When editing a place, the 'Feature Term' and 'LGA' should autofill in the same way they do on the search page. User should select from already existing options (but there's too many to make it a simple drop down).
Just noticed this in testing. Probably pretty easy to do.

**Comment by IanMcCrabb** [comment]
@yangli0516  will leave it with you as to whether we can fit this into the current sprint

**Comment by BillPascoe** [comment]
This has been done for 'add to layer' but not for 'edit' a place. This should be an easy copy paste, so best do it now or we won't get back around to it for a long time.

**Comment by yangli0516** [comment]
Test site updated.
