### ISSUE TITLE
3D viewer of polygon search silent fail

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#19]
BUG in 3D Viewer for search 'Texas' within a polygon drawn (example below). Note also there is an error loading in console, so we really should be catching and showing error messages instead of failing silently too. Could be the URL is too long for ESRI???

[https://tlcmap.org/3d/places.html?load=https%3A%2F%2Ftlcmap.org%2Fghap%2Fsearch%3Fcontainsname%3DTexas%26searchausgaz%3Don%26searchpublicdatasets%3Don%26polygon%3D141.892139%2B-28.81941%2C%2B154.366334%2B-28.31768%2C%2B152.389789%2B-34.826205%2C%2B150.413244%2B-37.869433%2C%2B142.770603%2B-36.327296%2C%2B140.662289%2B-34.428434%2C%2B140.837982%2B-28.395025%2C%2B141.892139%2B-28.81941%26format%3Djson](https://tlcmap.org/3d/places.html?load=https%3A%2F%2Ftlcmap.org%2Fghap%2Fsearch%3Fcontainsname%3DTexas%26searchausgaz%3Don%26searchpublicdatasets%3Don%26polygon%3D141.892139%2B-28.81941%252C%2B154.366334%2B-28.31768%252C%2B152.389789%2B-34.826205%252C%2B150.413244%2B-37.869433%252C%2B142.770603%2B-36.327296%252C%2B140.662289%2B-34.428434%252C%2B140.837982%2B-28.395025%252C%2B141.892139%2B-28.81941%26format%3Djson)

**Comment by yangli0516** [comment]
This is due to the '+' symbols in the URL not properly encoded. Have fixed this.

**Comment by HughCraig** [comment]
Tested, works fine.
