### ISSUE TITLE
Registration Error

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#193]
Reported by Isobel 19/6:

I am getting a 500 error when I try to register for a new account on GHAP

**Comment by yangli0516** [comment]
This is due to some hard coded database connection string which refers to the old 'pgsql2'.

**Comment by yangli0516** [comment]
Have applied the fix to both testing and production servers.

**Comment by BillPascoe** [comment]
Bill to test and confirm.
