### ISSUE TITLE
Add Search Results to Multilayer

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#196]
Enable user to add search results to their Multilayer.
User saves search.
User goes to Multilayer.
In the same way that a user adds a layer they can add Search Results from their saved searches.
See #197

**Comment by yangli0516** [comment]
Hi @BillPascoe ,

I assume saved searches are private to the owner. Even though the search result sets are public, the metadata on the result set such as 'Name' are private. 

Is the usage you mentioned above for public users as well or the multilayer is meant to be private?

**Comment by yangli0516** [comment]
Follow the following process:

- make the `name` of the search mandatory.
  - Make the column `name` in table `saved_search` not nullable.
  - Add the red asterisk (*) to the name field in the saved search form
  - Validate the name is filled upon save.
- Create a new migration to create table `collection_saved_search`.
  - It should contains the columns `collection_id` and `saved_search_id`.
  - Create the relationships on models `Collection` and `SavedSearch`.
- In page `myprofile/mycollections/{id}`, add a button named "Add a saved search" button after the button "Add a layer".
  - When the button is clicked, display a list of saved search (owned by the current user) to select. (similar to the adding a layer form).
  - When submitting the form, save the relationship in the table `collection_saved_search`
  - When listing a saved search in the table in this page
    - The "Name" column should display the name of the saved search and link to the actual search result page (determined by the `query` propery).
    - The "Size" column should display the number of results (from the `count` property).
    - The "Type" column should display the text "Saved search"
    - "Created" and "Updated" column use the `created_at` and `updated_at` properties.
    - The "View map" column should have list of view links to visualise the search results.
    - The "Remove" column should have the button to unlink the saved search from this multilayer.
- In page `/publiccollections/{id}`, list the saved search in the table with the similar manner.
- In the GeoJSON feed of the multilayer when used in views, if the multilayer contains a saved search, add the saved search inside the `datasets` array.
  - The `name` property should be the `name` of the saved search.
  - The `jsonURL` should be the JSON output of the search results (e.g. `https://[test-ghap.tlcmap.org/search?containsname=Hurstville&searchausgaz=on&searchncg=on&searchpublicdatasets=on&format=json](https://test-ghap.tlcmap.org/search?containsname=Hurstville&searchausgaz=on&searchncg=on&searchpublicdatasets=on&format=json`)

**Comment by MufengNiu** [comment]
> * L has the query string `line=route`, retain the order of places by their ID, and add the `lineString` geometry to the JSON connecting all places.
> * When the URL has the query string `line=time`, sort all places by time (the same way of sorting places in a layer in journey views), and add the `lineString` geometry to the JSON connecting all places.
> * When the URL has the query string `sort=start`, sort all places by start time (the same way of sorting places in a layer in timeline views).
> * Check the views work

"Hi @yangli0516, forgot to ask this during today's meeting. For this step: 'Make the column name in table saved_search not nullable.'  should we also create a migration to provide some default values for existing null entries?"

**Comment by yangli0516** [comment]
> > * L has the query string `line=route`, retain the order of places by their ID, and add the `lineString` geometry to the JSON connecting all places.
> > * When the URL has the query string `line=time`, sort all places by time (the same way of sorting places in a layer in journey views), and add the `lineString` geometry to the JSON connecting all places.
> > * When the URL has the query string `sort=start`, sort all places by start time (the same way of sorting places in a layer in timeline views).
> > * Check the views work
> 
> "Hi @yangli0516, forgot to ask this during today's meeting. For this step: 'Make the column name in table saved_search not nullable.' should we also create a migration to provide some default values for existing null entries?"

Yes, make a new migration file make the changes on the `name` column (Don't modify it on the existing migration file). Make the column not nullable and set its default value to "Search".
