### ISSUE TITLE
X to close video guide pop up.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#203]
I said many times that the video introduction to GHAP should not appear when you first load the home page and everyone seemed to agree in the end, but it still does (you need to clear cache to see this happen). Perhaps everyone wants it to remain, in which case, ok, I lose. But, if it is there it needs to have a little 'x' in the top right corner to close the pop up. The user can easily click outside of the video to close it, but if they don't realise this, they will look for the little 'x' to close the window and be annoyed they have a pop up they can't close.

**Comment by yangli0516** [comment]
Test site has been updated.
