### ISSUE TITLE
Edit Dates broken

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#207]
If the date field has only a year in it, instead of a full date with month and date, when I open that place to edit it, it tries to translate it into a full date and gives completely wrong date. If I didn't notice and saved it, it would save the wrong date.
Eg: Create or Edit a place. Add start or end date 1935. Save.
Edit this place again, and the date becomes 2023-07-13.

**Comment by yangli0516** [comment]
Test site updated.

**Comment by BillPascoe** [comment]
This has introduced another problem. If I try to edit a date that is a valid TLCMap date, but an unusual date such as 25,000BC which is expressed as -25000, then the edit interface says "Date Start must be in valid format". 
Note that many systems, and software packages, do not accept valid but unusual dates. Eg: they might not allow dates before 1900, or before the Unix epoche, or years that are not 4 digits, or years that are BC. However, it is essential to TLCMap to allow all dates, and we have had to build in special handling for this. (eg: this is why the start and end date field are text not date fields, and we have custom javascript validation on this field etc). 
See [https://tlcmap.org/help/developers/] for summary of valid TLCMap dates.

**Comment by yangli0516** [comment]
Test site updated.
