### ISSUE TITLE
Check for test-ghap in live environment

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#208]
When trying to get people signed up to accounts at a recent workshop. A few people ended up on the test-ghap.tlcmap.org site instead of the ghap.tlcmap.org live site. I looked at the confirmation email, and other links but I couldn't find any way this could have happened, so I'm not sure what happened. Please double-check that there is nothing in the code and there is nothing on the live site config that would provide or redirect anyone to test-ghap.tlcmap.org. Let Bill know if you can or can't find anything.

**Comment by MufengNiu** [comment]
Haven't found any redirect to the testing site from the GHAP codebase
