### ISSUE TITLE
Upload broken by nbsp in coordinate field.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#212]
If a CSV file has an nbsp in a coordinate field, the upload fails because the nbsp makes it seem like text instead of a number and the error reports: " invalid input syntax for type double precision: "-33.861944 "".
This is hard for the user to diagnose as they can't see the white space in the spreadsheet.
When importing spreadsheet, sanitise coordinate and any numeric input by stripping whitespace, or non-numeric characters. Be careful not to strip decimal points and minus sign.
See attached files as an example. Open them in text editor like Notepad++ to see the nbsp.
[TLCMLayer_DroughtJourney1.csv](https://github.com/HughCraig/GHAP/files/12157939/TLCMLayer_DroughtJourney1.csv)
[TLCMLayer_DroughJourney2.csv](https://github.com/HughCraig/GHAP/files/12157941/TLCMLayer_DroughJourney2.csv)

**Comment by yangli0516** [comment]
Test site updated.
