### ISSUE TITLE
Online census files gone

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#213]
Looks like in the transition to the new site we lost the census files we were hosting. They were under tlcmap.org/data/historicalcensus/
like this:
https://tlcmap.org/data/historicalcensus/NSW-1833-census.xhtml
We still have all the files but I can't figure out how to create a subdirectory and put them in it in Wordpress. I tried adding a plugin for creating media folders to upload files to, but it is blocking files of type .xhtml. To get around this it looks like I'd need to edit the config file that I don't have access to.
Let me know when we can create that path and upload files to it. (note there are quite a lot so we don't want to upload and then have to go through every file and set it's path individually).

**Comment by IanMcCrabb** [comment]
@HughCraig we have freed up schedules to start working on TLCMap support from Monday.  Please assign this to me if you'd like it to be in the first tranche of issues addressed.

**Comment by yangli0516** [comment]
Hi @BillPascoe,

We have two options here:

1. We host these census files the same way as quick tools and temporal earth in the Nectar server and create a subdomain for this as census.tlcmap.org. Then create redirect entries for the old census URLs to the new URLs.
2. WordPress.com does support SFTP for the business plan. Not sure what plan we are currently having (@isobel-andrews) and we may need to upgrade the plan if it's needed. Then we could upload the census files in a subdirectory under the WordPress site root.

Personally, I prefer the first approach as we are not sure how well WordPress site supports these static HTML pages. And it's more like hacking into a CMS platform to host static HTML pages.

Please let me know your thoughts about this.

**Comment by isobel-andrews** [comment]
> 2. WordPress.com does support SFTP for the business plan. Not sure what plan we are currently having (@isobel-andrews) and we may need to upgrade the plan if it's needed. Then we could upload the census files in a subdirectory under the WordPress site root.

FYI we are currently on the Business plan so no need to upgrade.

**Comment by yangli0516** [comment]
Have uploaded the census subsite to the Nectar server, the URL is:

https://census.tlcmap.org/

Also added all the redirect entries in the WordPress site.
