### ISSUE TITLE
Edit "Partners" page on website

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#214]
It would be good to update this page and make it a more comprehensive guide to partnerships and collaborations. See the attached document for a listing of possible inclusions. 
[Partners page.docx](https://github.com/HughCraig/GHAP/files/12206128/Partners.page.docx)

**Comment by isobel-andrews** [comment]
I have updated this page https://wordpress.com/page/tlcmap.org/185

Many images of different sizes are difficult to handle in Wordpress so I opted for tables. But let me know what you think.

**Comment by isobel-andrews** [comment]
Thanks Hugh. I have sized down the boxes a bit. Let me know when you have ARC and ARDC logos.

**Comment by HughCraig** [comment]
I have re-sent the emails. Let me know when you receive them -- maybe they are being trapped.

**Comment by isobel-andrews** [comment]
Oh thank you, no I had received them, I just completely lost them in my inbox. Cheers Hugh

**Comment by isobel-andrews** [comment]
Added ARC and ARDC. https://tlcmap.org/about/partners/
