### ISSUE TITLE
Order is broken on re-upload CSV

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#217]
We have a good way of updating CSV files by down loading and re-uploading while preserving the id. However, if I download the CSV of a layer edit one record, then upload again, it correctly updates that record but the order of records is broken. The one edited goes to the end. This means a journey route gets broken. 
Eg: On the 'Overlander' layer
https://ghap.tlcmap.org/publicdatasets/87
I downloaded, edited 'Darwin' and reuploaded. The modified location Darwin now appears at the end of the journey instead of the start. ie: instead of going from Darwin to Singapore, it now starts in Singapore, makes its way to London, then comes all the way back to Darwin.
https://views.tlcmap.org/journey.html?line=route&load=https://ghap.tlcmap.org/publicdatasets/87/json
We should also enable the person to change the order in a downloaded spreadsheet.
When fixing this, consider adding a column for 'sort order', because in future we will probably want to enable people to change the order through the user interface. Eg: if I don't upload a CSV but add a few sites through the add place form, and then decide they should be in a different order.
Adding a column for 'sort order' would also mean when I download the spreadsheet, I can just modify that field. 
When uploading a CSV file for the first time, the sort order should be assumed to be the order the records appear in the spreadsheet, and numbers incremented.
Sorting the records should be forgiving (it should not require strict ordering with no conflicts and blanks). ie: if we simply use build in database sort queries etc, it should be ok - if two sort order numbers are the same, the order won't be predictable but it won't fail, and ones without a sort order will either be at the end or beginning. Then if user notices sort order looks strange they can at least find the reason and fix it themselves.

**Comment by MufengNiu** [comment]
By fixing issue #188 we have preserved the order of places by sorting based on TLCMap ID.
For enabling users to change the order of places in the CSV upload. we think it is better to do this with the "changing order in user interface" feature.

**Comment by BillPascoe** [comment]
I'm making this deploy because it should be deployed to fix the way edits break the order but we still need a ways for user to change order. I will create another issue for that.
