### ISSUE TITLE
'Adding a collaborator' to a layer is broken

### ISSUE THREAD

**Issue by isobel-andrews** [HughCraig/GHAP#220]
Clicking 'Add a collaborator' on a layer prompts you to generate a share link that can be manually copied and shared or automatically emailed to someone else. This link doesn't work (see extensive examples from Sam Happe below). Also, if you try and use the field 'We can also email this link to your collaborator for you!', the emails are not received.

Example links:
Arms: [ghap.tlcmap.org/myprofile/mydatasets/join/6DkPXblDZyNbQ4eTV4NbHGTH8](http://ghap.tlcmap.org/myprofile/mydatasets/join/6DkPXblDZyNbQ4eTV4NbHGTH8)

Cash: [ghap.tlcmap.org/myprofile/mydatasets/join/iAh9P4vc9QtCuuHOw1E8dzE9z](http://ghap.tlcmap.org/myprofile/mydatasets/join/iAh9P4vc9QtCuuHOw1E8dzE9z)

Furniture: [ghap.tlcmap.org/myprofile/mydatasets/join/ZiKUsWZ1AKA13KGSc0WQCzddZ](http://ghap.tlcmap.org/myprofile/mydatasets/join/ZiKUsWZ1AKA13KGSc0WQCzddZ)

Jewellery: [ghap.tlcmap.org/myprofile/mydatasets/join/OFL7ruGo5VwlPuWY4ul6hgJt5](http://ghap.tlcmap.org/myprofile/mydatasets/join/OFL7ruGo5VwlPuWY4ul6hgJt5)

Portrait Miniatures: [ghap.tlcmap.org/myprofile/mydatasets/join/LSqrp93uNWcYHaE1sPiI8ssLW](http://ghap.tlcmap.org/myprofile/mydatasets/join/LSqrp93uNWcYHaE1sPiI8ssLW)

Portrait Paintings: [ghap.tlcmap.org/myprofile/mydatasets/join/w5LZBNLcevKyW9BmLWNyhleig](http://ghap.tlcmap.org/myprofile/mydatasets/join/w5LZBNLcevKyW9BmLWNyhleig)

Prints: [ghap.tlcmap.org/myprofile/mydatasets/join/tKNk0BJ67Y50aw13SgjfUHNZJ](http://ghap.tlcmap.org/myprofile/mydatasets/join/tKNk0BJ67Y50aw13SgjfUHNZJ)

Textiles: [ghap.tlcmap.org/myprofile/mydatasets/join/D8WlSqXgTj1DjqlwVzu6VbfM5](http://ghap.tlcmap.org/myprofile/mydatasets/join/D8WlSqXgTj1DjqlwVzu6VbfM5)

Timepieces: [ghap.tlcmap.org/myprofile/mydatasets/join/bW4bB7a5ONwQutgib2nKnKd3I](http://ghap.tlcmap.org/myprofile/mydatasets/join/bW4bB7a5ONwQutgib2nKnKd3I)

Transportation: [ghap.tlcmap.org/myprofile/mydatasets/join/A4H5khfhN93aqLx895tDIcV9D](http://ghap.tlcmap.org/myprofile/mydatasets/join/A4H5khfhN93aqLx895tDIcV9D)

**Comment by IanMcCrabb** [comment]
@HughCraig Are you OK with us adding this to the development ticket?

**Comment by HughCraig** [comment]
Yes, I agree it is good to deal with bugs as a priority.

**Comment by yangli0516** [comment]
Related to #88 

I think we originally deprecated this feature as I remember it was not working properly that we decided to hide these features from the UI. The collaboration feature may needs a re-design. It's probably better to just hide these buttons from the UI for the moment.

**Comment by BillPascoe** [comment]
Yes hide these buttons for now. When they were made it was done running out of time, so is messy and broken. This needs a complete redesign in how it works. How it works should be similar to how other applications work in enabling multiple people to edit the same thing (principle of least surprise). It would involve granting edit access to layers, multilayers and search results to other users. The UI could simply be:
- after your friend has created an account (so we don't need email invite) 
- go to layer, multilayer or saved search
- look up your friend by their email address or username, and click 'grant access'. 
It can be simple all-or-nothing access no complicated levels of access. 
This is now higher priority than before with more people in teams using the application.

**Comment by IanMcCrabb** [comment]
@MufengNiu Please just hide the buttons for now and then reassign this issue to me.  I will put it in the back burner for design review.

**Comment by yangli0516** [comment]
The button is temporarily removed for the moment. Test site updated.
