### ISSUE TITLE
Allow new user access to features without email verification.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#232]
At present a new user creates account and tries to add layer but it says 'Verify Email'. They can't do anything without verifying email. Emails are still getting blocked in clutter and spam etc, and sometimes overnight. We need to investigate that too, but it's very hard. In a workshop environment when you get people to create account they should be able to just use it straight away. So when someone has created account, they should immediately see the nav banner with 'My Layers' etc. These should also be active without having to verify account. If someone forgets password they can do password reset. If they put a typo in their email address when they created account, that's too bad, they can figure that out and create account again. If someone creates account with fake email to put dodgy stuff in, that is rare and we will handle that by having admin able to block account.
This is a high priority as it will stop people signing up and using TLCMap and is the biggest stumbling block in the first account creation step in workshops.

**Comment by IanMcCrabb** [comment]
@HughCraig will leave this with you to assign to us

**Comment by yangli0516** [comment]
@MufengNiu , please go ahead on this and make an env configuration to enable/disable the email verification/account activation process.

**Comment by yangli0516** [comment]
This issue has been addressed through the middleware level. A new env setting `NEW_ACCOUNT_EMAIL_VERIFICATION` has been added to disable the `verified` middleware.

Test site has been updated and the email verification setting has been disabled.

**Comment by yangli0516** [comment]
The email verification has been disabled for the production site.
