### ISSUE TITLE
Remove video from first landing on GHAP front page.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#233]
If a person goes to https://ghap.tlcmap.org for the first time, it immediately plays the video. The user has to click out to get rid of it (it doesn't load automatically on later visits). This is annoying, and can be a problem in workshop situation, as people to the page and it plays automatically and they don't have volume turned down, and they panic to close it it.
The video is easy to access for those who want it from the 'Quick Start' link and in the GHAP Guide.

**Comment by IanMcCrabb** [comment]
@HughCraig will leave this with you to assign to us

**Comment by IanMcCrabb** [comment]
Implement with config setting in .env

**Comment by yangli0516** [comment]
Test site updated.
