### ISSUE TITLE
Saved search table column migration error

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/GHAP#240]
I got the following message when running the migration `2023_08_18_172937_update_name_column_in_saved_search_table`:

```
Changing columns for table "tlcmap.saved_search" requires Doctrine DBAL; install "doctrine/dbal".
```

Please check whether missing "doctrine/dbal" is the actual cause, and include it in the `composer.json`.

Note: the server is using PHP 7.4. Please be careful about the dependency version.

**Comment by yangli0516** [comment]
Related to #196

**Comment by MufengNiu** [comment]
Resolved by including "doctrine/dbal" library

**Comment by yangli0516** [comment]
Test site updated.

**Comment by BillPascoe** [comment]
I'm unable to test the migrations, but since the related task is 'save search' and that seems to work, I'll mark to deploy.
