### ISSUE TITLE
Bugs with search within layers

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/GHAP#241]
If I select one or more layers in the advance search as the search scope, and empty the layer text input. Then the search scope is still set to that layer once I click the search button.

There must be some issues with the data update of the layer autocomplete widget. Please have a test to see when deleting or updating the text within the widget, the background data is actually updated.

**Comment by yangli0516** [comment]
Related to #197

**Comment by MufengNiu** [comment]
Resolved.
The "Change" event is only triggered when the element has lost focus. Changed to listening to "input" event.

**Comment by yangli0516** [comment]
Test site updated
