### ISSUE TITLE
Search/Filter Enhancements - Extended Data

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#244]
Search/Filter:

Extended Data: A more complicated means of constructing searches. User adds search criteria one at a time, entering:
Attribute name, Condition, Value
The options for 'Condition' should be: textmatch, >, <, =, before, after
textmatch should be a 'contains exact match' style search. Eg: in SQL '%mytext%'.
before and after would be date comparisons
Eg:
Population, >, 100
or
ArtistStyle, text match, "Surrealism"
The user selected conditions are combined with AND clauses.
Eg user could set up a filter on census data like:
Population > 100 AND Population < 500 AND Religion textmatch 'Orthodox'
(This is important to combine with Search/Filter within layer, enabling users to interactively explore and customise subsets of their data without an exponential 'complexity' need to upload many different sets of the same data to get different views. It is crucial that this be in the get parameters for passing into views, so that a user can set up various views of filtered subsets of their data that they can then add to Multilayers for highly customisable comparisons. User can build multilayers from such results.)
There is a risk this may result in long URL query strings that exceed the max size of a URL of 2048 but for most purposes it should be fine.
Suggestion on how to do this in a better way are welcome.

**Comment by IanMcCrabb** [comment]
Outstanding tasks not dealt with in #235

**Comment by MufengNiu** [comment]
Format for extended data search :

           attribute.   condition   value
1.                          textmatch                      e.g. name textmatch  map.   text textmatch 'Facebook'
2.                               =                               e.g.  name  = map
3.                               <                               numeric input only.  e.g.  Cost > 500
4.                               >                               numeric input only.  e.g.  Cost < 500
5.                            before                         date format only(YYYY-MM-DD , YYYY-MM , YYYY) e.g Start before 1995-12   End before 2012-05-05
6.                            after                            date format only(YYYY-MM-DD , YYYY-MM , YYYY) e.g Start after 1995-12   End after 2012-05-05

Searches can be combined by "AND" clauses such as  Cost > 500 AND Start after 1995-12

**Comment by yangli0516** [comment]
Test site updated

**Comment by BillPascoe** [comment]
Testing on Selections from the Edith Cowan University Art Collection
https://test-ghap.tlcmap.org/myprofile/mydatasets/90

Region textmatch 'Pilbara' - PASS
Region textmatch 'Pilb' - PASS
'Region' textmatch 'Pilbara' - FAIL
'Artwork Title' textmatch 'Wittenoom Miners' - FAIL
'Artwork Title' textmatch 'Wittenoom Miners' - FAIL
Region textmatch 'Wheatbelt' AND Firstname textmatch 'Shane' - PASS
Date > 2013 - PASS
Date < 2015 - PASS

So please allow for, or require that the attribute be in quotes too. This is probably necessary to handle attribute names with spaces in them.

This will most likely used in combination with searching within a particular layer, so put this search field directly under 'Layers'.
The syntax will require documentation, so add an inline question mark next to 'Extended Data' with the text: "This enables nuanced search and map creation within layers and needs special sytax, see under 'Search' in the GHAP Guide." and link to https://tlcmap.org/help/guides/ghap-guide/ (we will add this to the guide when we deploy).

Please check this is safe from SQL dependency injection.

In future we may make the user interface for this a bit clearer, showing the user a Attribute field a Comparison operator field (drop down select), and a Value field. With a little + icon to add more comparison conditions. But for the moment go ahead with it as it is so we can have some thing working and not hold things up.

**Comment by yangli0516** [comment]
Test site updated.
