### ISSUE TITLE
Automate load of Layers from Paradisec  

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#251]
We are now ready to load the data for Paradisec into GHAP.    Below is from Jiohn Ferlito

The best way to crawl the collection would be to first crawl https://catalog.paradisec.org.au/collections.geo_json
That will give you the geojson for all the collections.

You can pull the collection IDs out of that json
e.g. curl https://catalog.paradisec.org.au/collections.geo_json | jq '.features | .[] | .properties.id'

then for each collection id e.g. NT1 you can crawl https://catalog.paradisec.org.au/collections/NT1.geo_json

Which will give you all the items.

**Comment by IanMcCrabb** [comment]
Plan is to :

Generate a single layer with a point for each collection using https://[catalog.paradisec.org.au/collections.geo_json](https://catalog.paradisec.org.au/collections.geo_json)

Generate a layer for each of the 600 or so collections by iterating through e,g https://catalog.paradisec.org.au/collections/NT1.geo_json  This will have points and some metadata for each item in that collection.

We can use the new saved search feature for enquiries that want to find items of a particular language across all collections...

**Comment by IanMcCrabb** [comment]
@yangli0516 to spec approach to automating the import

**Comment by yangli0516** [comment]
@IanMcCrabb , we are going to need an owner for these layers. Do we make Hugh as the owner or you want to be the owner?

**Comment by IanMcCrabb** [comment]
@yangli0516  Figure the layer owner can be Professor Bill Palmer who is sponsoring the project and wants to research the dataset.  https://www.newcastle.edu.au/profile/bill-palmer

**Comment by yangli0516** [comment]
This could be created as an external PHP script, which reads data from the API directly and create layers based on the data returned.

Firstly, create a layer (dataset) from collections GeoJSON.

Populate the properties for the layer:

- `name`: "PARADISEC collections"
- `description`: ???
- `public`: `true`
- `creator`: ???
- `publisher`: ???
- `contact`: ???
- `source_url`: ???
- `license`: ???
- `rights`: ???
- `recordtype_id`: 1 (Other)
- `linkback`: ???
- `created_at`: Current time
- `updated_at`: Current time

Then create the ownership in the `user_dataset` table:

- `user_id`: The user ID of the nominated owner.
- `dataset_id`: The ID of the layer just created.
- `dsrole`: "OWNER"
- `created_at`: Current time
- `updated_at`: Current time

For each feature from the GeoJSON, create the place (dataitem) based on that feature:

- `dataset_id`: The ID of the layer just created.
- `title`: feature property `name`
- `recordtype_id`: 1 (Other)
- `description`: feature property `description`
- `latitude`: from feature coordinates
- `longitude`: from feature coordinates
- `datestart`: convert feature property `udatestart` to date string "yyyy-mm-dd"
- `dateend`: convert feature property `udateend` to date string "yyyy-mm-dd"
- `source`: feature property `url`
- `external_url`: feature property `url`
- `extended_data`: constructed XML
  - `Languages`: feature property `languages`
  - `Countries`: feature property `countries`
- `datasource_id`: 1 (GHAP)

Once the place record is saved, we need to create the `uid` for that record. Check the logic from `\TLCMap\Http\Helpers\UID::create` and use the place record `id` and prefix `t` to populate and update the `uid`.

**Comment by yangli0516** [comment]
The next step is to create layers for all collections. We can loop through all the features from the collections GeoJSON. With the `id` of the feature, construct the GeoJSON URL for that collection in the format of `https://catalog.paradisec.org.au/collections/{CollectionID}.geo_json`.

With the collection GeoJSON data, first create the layer (dataset) for that collection:

- `name`: `name` from the feature collection metadata
- `description`: `description` from the feature collection metadata
- `public`: `true`
- `creator`: ???
- `publisher`: ???
- `contact`: ???
- `source_url`: this can be the `url` property from the top level collections GeoJSON.
- `license`: ???
- `rights`: ???
- `recordtype_id`: 1 (Other)
- `linkback`: the same as the `source_url`
- `created_at`: Current time
- `updated_at`: Current time

Then follow the same process described above to create the ownership, places, and `uid`.

**Comment by yangli0516** [comment]
@IanMcCrabb , may need your input on those property mapping with question marks above.

**Comment by yangli0516** [comment]
> @yangli0516 Figure the layer owner can be Professor Bill Palmer who is sponsoring the project and wants to research the dataset. https://www.newcastle.edu.au/profile/bill-palmer

This has to be a valid user account in GHAP, which is listed as "Contributor" in the layer detail page. And only the owner has the rights to modify the layers he owns in GHAP. 

Currently I don't see Bill having an account in GHAP.

**Comment by IanMcCrabb** [comment]
OK, I'll organize Bill Palmer to create an account.  I'll liaise with Paraadisec folks on the ?? and add edit the spec above.

**Comment by yangli0516** [comment]
@MufengNiu, have updated the mapping specification above, please use it to validate your output.

**Comment by IanMcCrabb** [comment]
@MufengNiu investigate data issue and report on layers with empty names

**Comment by MufengNiu** [comment]
Hi @yangli0516 , @IanMcCrabb . Have tried a few times later and all layer's names are complete. So it seemed to be an incomplete JSON due to internet issues.

**Comment by IanMcCrabb** [comment]
@MufengNiu great thanks.
