### ISSUE TITLE
Dev access to test-ghap

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#262]
Set up access to the test-ghap.tlcmap.org server for:

Kaine Usher: kaine.usher1@gmail.com
Ivy Zheng: zhengzhixin2016@gmail.com

They will need:
SSH
SFTP
sudo

Please ensure access is established by October 1. Please contact them directly to coordinate this, with exchanging security keys etc, as Bill will be consumed with other responsibilities.

Coordinating with Systemik on deployment for testing isn't workable. We are very short on time, and there would probably be weeks of lag in waiting for one side to find time. So it will work better if the devs do the install and set up testing, and document it, then there is a hand over for deployment to production, where on a scheduled day, TLCMap and Systemik staff work together to move into production. This will also confirm that the documentation is good.

**Comment by yangli0516** [comment]
@BillPascoe , I will organise the logins directly with Kane and Ivy. Please do keep in mind that if an application can sit by its own without GHAP, should consider setting up a dedicated server for it, which makes scaling, migration, debugging etc. a lot easier.

**Comment by BillPascoe** [comment]
@yangli0516  For the moment, all on the test-ghap will be a good way to get started quickly. There are three areas of activity:
Mobility: this will be closely integrated with GHAP, and be enhancements to GHAP database, UI and Views. Ivy will need to make these modifications in test-ghap.tlcmap.org
STMetrics: this will be an API for GeoJikuu. GHAP will directly call it. It will have some standalone features, but there is a good chance that to process efficiently it will call the GHAP database directly. Should this API be on the GHAP server in order to call the database, or is the database server running separately so that the STMetrics app should be hosted separately? The API could be accessible through stmetrics.tlcmap.org
Map Text: this will be standalone, so in future we should probably set up something like maptext.tlcmap.org

**Comment by yangli0516** [comment]
@BillPascoe , we currently only have a single server instance which hosts the GHAP production site, production database, test site and test database. If STMetrics API needs to interact with the GHAP database directly, it makes sense to put it in the same server.

**Comment by yangli0516** [comment]
Ivy's access has been set up on Mon 11/09

**Comment by yangli0516** [comment]
Hi @kainedusher , would you mind to act on this in order to get your access sorted. Details can be found from my previous email in terms of generating the keys.

**Comment by kainedusher** [comment]
Thanks @yangli0516. I now have access to the GHAP test server and can perform sudo commands.

Are there any particular guidelines I need to follow when working with the server?

**Comment by yangli0516** [comment]
@kainedusher , we will work on the internal documentations and guidelines in a later stage. Refer #284
