### ISSUE TITLE
Scheduled backup

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/GHAP#277]
Currently, both production and testing databases are not configured with proper backup strategies, which is great risk in a long term. Especially we are going to disable the email verification soon in the production site. Therefore, proper data recovery strategies should be set up as early as possible.

**Comment by IanMcCrabb** [comment]
@BillPascoe can you advise and assign to us if you need us to implement

**Comment by IanMcCrabb** [comment]
Cheers @yangli0516 cool idea to generate an RO-Crate

**Comment by yangli0516** [comment]
Have set up the cron job for testing site backup to run every day 3:00am server time. It has been configured to keep only 90 days backup files, as we have limited server disk space. Currently, each database backup file is around 30MB. Therefore, the maximum disk space it requires for 90 days backup of both test and production sites will be around 5.4GB. Keep in mind that we only have 30GB total disk space in our server.

Ideally, these backup files can go to the Object Store provided by Nectar. But it is a different topic which involves setting up to script to use Swift API to manage files uploading. We will consider this option later when we have disk space shortage.

After we make the next release to production, I will setup the same cron job for the production site. Let me know if anyone have different ideas about the number of days' backup we should maintain.

**Comment by yangli0516** [comment]
Have made a backup of the production site at 2023-09-22 12:22 PM.

@BillPascoe, to run a backup yourself, you can use the following artisan command:

```
php artisan export:rocrate:ghap
                            {--dir= : The path of the target directory to hold the RO-Crate archive. Default to the current directory}
                            {--name= : The file name of the RO-Crate archive. If not provided, a default name (timestamped) will be used}
                            {--pgdump=pg_dump : The path of "pg_dump" utility. Default to "pg_dump" as it is in the system path}
```

For example, to backup the production site, first go the production site root directory and run the command:

```
php artisan export:rocrate:ghap --dir=/path/to/target/directory
```

Once it's saved to the server, you can use SFTP to download it. All credential details are read from the `.env` file and won't be exposed in the backup files.

I will document more details about those artisan commands when we start the documentation process.

**Comment by yangli0516** [comment]
The cron job has been created for the production site on 28/09/2023.
