### ISSUE TITLE
Paradisec Layers on Production Site

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#292]
Please schedule to do this as part of the deployment of the next tranche of issue fixes

**Comment by MufengNiu** [comment]
@BillPascoe Have updated the import on the testing server with updated layer type and keyword (#294). Shall we run the import on the production server?

**Comment by BillPascoe** [comment]
In fixing #294 Mufeng noticed this other issue #301 so fix that one, then import to prod.

**Comment by IanMcCrabb** [comment]
@MufengNiu ready to move to production

**Comment by MufengNiu** [comment]
Have run the import on the production site. Layer owner is set to bill.palmer@newcastle.edu.au
