### ISSUE TITLE
PARADISEC Layer Subject Metadata

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#294]
For all PARADISEC Layer metadata, set:

Type = Media
Subject = PARADISEC, linguistics, language

(There needs to be a way to find all PARADISEC layers, so PARADISEC should be a 'subject' to all of these layer's metadata.
They should also have subjects relevant to the discipline, so "linguistics, language")

**Comment by IanMcCrabb** [comment]
@MufengNiu if you could enhance the layers with this additional metadata when you deploy to production

**Comment by MufengNiu** [comment]
Have updated the import on the test server.

**Comment by IanMcCrabb** [comment]
@MufengNiu Looks fine, but how would one search on layers that have PARADISEC as a subject value.?

**Comment by MufengNiu** [comment]
@IanMcCrabb  We don't have search for keywords or Layers/Multilayers functions yet. #260

**Comment by IanMcCrabb** [comment]
@MufengNiu ready to move to production

**Comment by MufengNiu** [comment]
Have run the import on the production site. Layer owner is set to bill.palmer@newcastle.edu.au
