### ISSUE TITLE
In App Editing Record

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#30]
This one is important for good UX.

**Problem:**
Users will sometimes just want to quickly add a record or several into the app without having to create and upload a spreadsheet. Also, they will often want to just quickly edit a single record to fix up a small mistake, without deleting the whole layer editing the CSV and reuploading - which would also destroy the uid for the URL making it not persistent.
However the user interface for this is not good at the moment. The input fields are single row and small so you can't see what you are typing. (this was an early design decision to try to make it like filling in a spreadsheet, but it turns out not so good).

**Solution:**
Instead it should pop up with a larger input window, with inputs in scrollable vertical form layout instead of row layout. Then you can have wide single lines for single line fields, and multiline textareas for multiline input like the description. This is familiar to users from many other web interfaces - you click 'edit' and it pops up with a form, with save and cancel buttons at the bottom, and an 'x' top right to close the window without taking any action.

This needs:

- an 'Add Place' form for when user clicks 'Add to a Layer' in the Layer editor, for create.
- an 'Edit Place' form for when the user clicks 'Edit' button, in the list of places when editing the layer. 

The 'help' question mark icon next to the 'Extended Data' field should say "Do no edit unless you understand what you are doing. Small errors may stop this layer working."
Include form validation for:

- TLCMap compliant date fields (YYYY; dd/mm/yyyy; yyyy-mm-dd. Allow days and months to be single digit, or to have a leading 0. Allow any number of years, eg: YYYYY, or YYY, and allow negative years for BC dates eg: -YYYYYY)
- Latitude and longitude fields
- URL fields

This should be deployed then followed by some others enhancements, which are listed as seperated issues:

- #174 Add map edit interface from cfadmin (ask Bill for the code). This enables user to either manually edit coordinates or click on a map to get coordinates.
- #175 Add date edit interface. This should be the TLCMap developed date editor (ask Bill) that enables any date to be picked from the calendar and or edited manually, and has none of the limitations common in other systems (eg: allow year only, dd-mm-yyyy, negative year, any number of digits in the year, etc, ie: any data can be made compatible with the ISO standard,)
- #176 Add WYSIWYG editor for textarea fields. Limit available edit options to heading level, italics, bold, add link, bullets. Nothing else.
- #177 Add 'Are you sure you want to delete?' confirmation to the 'delete' button.

**Comment by BillPascoe** [comment]
While doing this, as part of revision and improvement of handling records, also change the 'delete' workflow to include a prompt 'Are you sure you want to delete this place?' to avoid accidental delete. I'm putting this here instead of a separate issue, as the improvements to editing may involve completely removing the current in-row editing and delete systems, so it makes sense to revise/replace/improve the whole CRUD workflow at once.

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget

**Comment by IanMcCrabb** [comment]
@HughCraig we can get Yang to go ahead on #30 and work up scope on #174-177

**Comment by HughCraig** [comment]
Yes, sounds like an excellent idea
 Best wishes, Hugh.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by yangli0516** [comment]
Have done the initial development of this issue, which changes the display of user layers display and place edit form. Please have a look in the testing site.

Please note that the extended data editor and validation haven't been implemented as it may relate to other issues we are planning to implement. The following is the rough scope of the remaining issues and tasks:

- #174 Depending on the state of the existing code, it may take 1-3 days to integrate and configure.
- #175 Depending on the state of the existing code, it may take 1-3 days to integrate and configure.
- #176 Considering either using TinyMCE or CKEditor, takes 2 days to integrate and configure. Does this also apply to other forms like layers and multilayers?
- #177 Done already.
- Extended data editor: 1 day
- Validation: (client and server side) 1-2 days

**Comment by BillPascoe** [comment]
If I click the 'Add to layer' button it shows the default fields but it doesn't have an option to add 'Extended Data'. Also if I edit a place that doesn't have extended data, there is no option to add it. Please include these two things.

**Comment by yangli0516** [comment]
> If I click the 'Add to layer' button it shows the default fields but it doesn't have an option to add 'Extended Data'. Also if I edit a place that doesn't have extended data, there is no option to add it. Please include these two things.

The extended data editor wasn't pushed to the server. Now it's available in the testing site.
