### ISSUE TITLE
THE TLCMap for the front page

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#327]
THE time layered cultural map.
Create a map view for the front page that present a very simple interface to GHAP data. After much discussion the aim is to provide the simplest possible 'Time Layered Cultural Map'. It should be the simplest and easiest way to answer the question 'What is here?' with culture as the answer. (Similarly Google maps will answer with businesses etc)

This could work in one of two ways and we still need to decide which. One of the main constraints is that we cannot present all the records on the map by default because there's hundreds of thousands, so results must be limited.

The main page shows the normal heading and navigation at the top, and in the main part of the page, a map. This is what people actually expect to find when they arrive - a time layered cultural map. 
The navigation options and maybe some very minimal other prompts (such as 'full search with GHAP', and a 'create maps' button - to be figured out) will provide access to all the other features, tools, guides, workflows, etc etc.

**Option 1. Manual Search (user enters word to see results)**

- Above the map is a single text field search box, and a search button.
- No dots are shown, just the map.
- User enters a search and clicks button.
- It calls the GHAP API with a broad search - fuzzy, include 'description' (and later when we feature is added, the layer metadata), with a maximum search results. If the maximum is reached it should report (Only showing <max> results, for full search use GHAP).
- Load results on map view.

**Pro:** Easy to achieve with existing functionality - it's just an embedded map view with dynamic loading of the json query to the map using the GHAP WSAPI.
**Con:** First thing user sees is an empty map.

**Option 2. Auto Search (Random Limited Results, zoomed to user location)**

- The main page shows the normal heading and navigation at the top, and in the main part of the page, a map. This map shows dots from GHAP obtained like this:
- Attempt to get the user location from their browser (this depends if the user has allowed this or restricted it for privacy). If the user has not allowed this set the map to centre and zoom to the whole of Australia.
- If we could get user location, centre and zoom to that location (zoom level to be determined).
- The script will derive the bounding box that would fit the map window, and send a bounding box query to GHAP WSAPI, limited to a maximum number of results. Possibly this search should request 'random' results from the database to avoid possibility of just the same results from a single very large layer being returned all the time.
- If the user zooms in or out, it resends the query and reloads results. For this reason it should be limited to a fairly low max amount of results to avoid users who are wildly zooming in and out and moving around spamming the database causing accidental DOS attack. (also more than a hundred points is too noisy on a map anyway).
- This way it dynamically loads cultural stuff relevant to anywhere the person is looking. This is analogous to Google maps, where you zoom in and it starts showing more and more information.

**Pro:** User sees clickable culture on the map immediately.
**Con:** A little harder to achieve, having to figure out bounding box, etc. Possibly the dynamic loading in response to rapid zooming and moving of the map might be smooth, might be too glitchy trying to catch up with itself.

**Comment by HughCraig** [comment]
I like the idea of the page opening with content already loaded, i.e. a version of Option 2. That pre-loaded content would give the user some guidance and prompting to do their own search. Could we prepare 100 search terms which would each yield an interesting set of points of about the right size, and have a random choice made from them each time?
I can see the attraction of zeroing in on the user's location if that is feasible but think a random choice among meaningful options would work even if not selected for the user's location (there is the appeal of the exotic anyway, as well as the appeal of the local, i.e. even the zooming-in bounding boxes could be randomly determined).
Ideally the user sees something interesting on first landing on the page and gets the idea of the sort of thing that you can search for.

**Comment by IanMcCrabb** [comment]
Isobel Notes 

Brief:
•	Default base layer, search box with a button – functionality is it constructs GHAP search that is whatever the default is on GHAP currently (GHAP, ANPS, NCG….)
•	Advanced search button – goes to GHAP front page
•	Map attempts to geolocate user, randomly loads maximum 500 locations – at a certain zoom level, tbd
o	Randomness mechanism – DB query can be built randomly
o	Zoom level sweet spot is important! – size of Sydney basin?
•	Get bounding box of current map window – then construct the GHAP query using the bounding box to get parameters
•	If geolocation fails, leave map blank – user will intuitively search, which will search GHAP and load results
•	Potential for category buttons – all categories (‘place types’) shown – user can select one or multiple to search all records in layers of that type within current map window. 
Deadline – April 18
Set meeting for 11-12/3

**Comment by IanMcCrabb** [comment]
•	Another approach is to copy what google and bing do:
•	Default map shows default locations independent of GHAP, ANPS and NCG 
•	Default search would include is GHAP, ANPS and NCG but able to switch any on/off 
•	Curate a set of Category tags that correlate to Restaurants and Parking (Indigenous, Performance, Language….)  
•	Leverage the type field on layers (inheritance on places) and on places 
•	When one clicks on one of these tags search and display all places withing the bounding box in layers that are thus tagged.
•	Would also need an All tag and a drop-down list of other Categories.
 
•	Categories could be saved per user …. 
•	We could come up with a way of bubbling the most popular to the top …. 
Search Use Case
•	So if I search for Shepparton, the map should zoom to Shepparton and show ne everything form every layer located around Shepparton.
•	Can turn on/off GHAP, ANPS and NCG
•	I should be able to turn off All Categories and instead click on Indigenous and Performances and see pins for only these around Shepparton
•	As I traverse the map then on ly pins for Indigenous and Performances are displayed.

**Comment by IanMcCrabb** [comment]
Isobel Notes

Brief:
• Default base layer, search box with a button – functionality is it constructs GHAP search that is whatever the default is on GHAP currently (GHAP, ANPS, NCG….)
• Advanced search button – goes to GHAP front page
• Map attempts to geolocate user, randomly loads maximum 500 locations – at a certain zoom level, tbd
o Randomness mechanism – DB query can be built randomly
o Zoom level sweet spot is important! – size of Sydney basin?
• Get bounding box of current map window – then construct the GHAP query using the bounding box to get parameters
• If geolocation fails, leave map blank – user will intuitively search, which will search GHAP and load results
• Potential for category buttons – all categories (‘place types’) shown – user can select one or multiple to search all records in layers of that type within current map window.
Deadline – April 18
Set meeting for 11-12/3

**Comment by BillPascoe** [comment]
DONE! :-)
