### ISSUE TITLE
Bug in Journey line

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#329]
There is a bug with the fix for the line crossing 180 longitude. I didn't notice this when I tested sorry, as I must have tested on a layer that did not show the problem.
The problem is that some points are not connected by a line at all. This happens on some layers. An example is this map: 
1822 Duperrey expedition, route of the Coquille
[https://views.tlcmap.org/v2.0.1/journey.html?load=https%3A%2F%2Fghap.tlcmap.org%2Flayers%2F545%2Fjson%3Fline%3Dtime](https://views.tlcmap.org/v2.0.1/journey.html?load=https%3A%2F%2Fghap.tlcmap.org%2Flayers%2F545%2Fjson%3Fline%3Dtime)
There are many points around Melanesia that are not connected by a line.

**Comment by IanMcCrabb** [comment]
@MufengNiu if you might close this if its complete

**Comment by HughCraig** [comment]
Not working atm -- see Bill's example above.

**Comment by MufengNiu** [comment]
Hi @yangli0516, can you update the version of the Mapview for the testing site to the latest version?

**Comment by yangli0516** [comment]
This has been updated to the test site. Please test.

**Comment by MufengNiu** [comment]
> Not working atm -- see Bill's example above.

Currently, the change is only available on the testing site, please see: https://test-ghap.tlcmap.org/layers/1348

**Comment by IanMcCrabb** [comment]
@HughCraig if you are OK then we can tag this with Deploy assign this to @BillPascoe...

**Comment by HughCraig** [comment]
Sounds good.
