### ISSUE TITLE
Review Responsive Design for UX

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#33]
Map is a little larger now.

I’ve been toying around with some ideas on paper that I think will be very similar to the current layout but much better. I will present these as a mockup after I implement more important functionality.

My ideas below:

New design makes better use of vertical space near the search fields to give us more map space.

New design also puts filters and map area search text boxes into the same column separated by tabs that swap between the content. This means the entire map area search text boxes area can also be map space.

New design will more appropriately use bootstrap columns, which will automatically scale to the screen size (eg on a phone, columns will vertically stack instead of side by side as there isn’t enough horizontal space).

New design will be more phone friendly in general (locking to section, “go up” buttons, etc).

**Comment by IanMcCrabb** [comment]
Figure we need to consider these ideas as part of the Site UI phases

**Comment by BillPascoe** [comment]
Map has been redesigned since this, so it's no longer relevant.
