### ISSUE TITLE
Apply journey line crossing 180 fix to multilayers

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#330]
The fix for crossing 180 longitude was not applied to multilayers. Apply the fix to multilayers.

**Comment by IanMcCrabb** [comment]
@MufengNiu if you might close this if its complete

**Comment by HughCraig** [comment]
Not working atm -- see https://views.tlcmap.org/v2.0.1/collection-journey.html?load=https%3A%2F%2Fghap.tlcmap.org%2Fmultilayers%2F57%2Fjson%3Fline%3Droute

**Comment by yangli0516** [comment]
This has been updated to the test site. Please test.

**Comment by MufengNiu** [comment]
> Not working atm -- see https://views.tlcmap.org/v2.0.1/collection-journey.html?load=https%3A%2F%2Fghap.tlcmap.org%2Fmultilayers%2F57%2Fjson%3Fline%3Droute

Currently, the change is available in the testing site, please see: https://test-views.tlcmap.org/dev/collection-journey.html?load=https%3A%2F%2Ftest-ghap.tlcmap.org%2Fmultilayers%2F18%2Fjson%3Fline%3Droute

**Comment by BillPascoe** [comment]
Looks good. Please deploy.

**Comment by IanMcCrabb** [comment]
@BillPascoe will leave it with you to deploy to production.
