### ISSUE TITLE
Unable to restart the test server

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/GHAP#340]
The server was automatically shut off and wasn't able to restart the instance.

**Comment by yangli0516** [comment]
The compute node your instance is running on has a hardware error and it is unable to boot. Fortunately the service engineer is due tomorrow morning to repair the server, so I hope to have it up and running by lunchtime. I'll start all the instances on that node once we've checked everything is ok.

Please be patient while we confirm everything is ok.

Kind regards,
Glenn
The ARDC Nectar Cloud helpdesk team

**Comment by yangli0516** [comment]
Unfortunately the engineer was unable to repair the server despite being onsite for over 4 hours. Looks like it will be a few more days at least.

If you have a recent snapshot you could launch a new instance from that. Unfortunately as the server is down you can't make a new snapshot. This tutorial shows how to do that https://tutorials.rc.nectar.org.au/launching-virtual-machines/01-overview

Kind regards,
Glenn
The ARDC Nectar Cloud helpdesk team

**Comment by yangli0516** [comment]
Will wait a few more days to see whether they can solve the problem.

**Comment by IanMcCrabb** [comment]
@yangli0516 if you might close this if the test server is OK.
