### ISSUE TITLE
Advanced search

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#389]
Maybe we could reorganise this so that it only takes up a narrow horizontal band of the screen leaving room for the map
Fonts look a little janky.  Maybe we can tidy up fonts and sizes    
Maybe a default behaviour is that the advanced search doesn't disaperar so that one can do searches and see the results without going back and forth

**Comment by isobel-andrews** [comment]
[TLCMap homepage - Advanced Search.pdf](https://github.com/user-attachments/files/16051841/TLCMap.homepage.-.Advanced.Search.pdf)

@MufengNiu I have attached the wireframes. Basically I would like the ability to only add the filters that the user wants.

Let me know if you have any questions or problems.

**Comment by IanMcCrabb** [comment]
Nice work

**Comment by IanMcCrabb** [comment]
OK
