### ISSUE TITLE
Advanced Search and Category Toggles

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#395]
Let's move the 3 toggles NCG, ANPS and GHAP (renamed to Layers) from Advanced search up immedialty below the toggle for Map, Cluster and List and color code them to match the place colors

These would need to control auto population of the map and also work with the advanced search

We can then do another redesign of Advanced Search to make it even cleaner

**Comment by MufengNiu** [comment]
Drop text "Advanced search". move arrow to left most

**Comment by IanMcCrabb** [comment]
OK
