### ISSUE TITLE
Integrate STMetrics

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#40]
When looking at my datasets, I can simply choose the option to open in STMetrics and look at the stats.
We migrated to Postgres with PostGIS to make this easier.
This is a big but important job. This might have to wait for a block of funding. Ask Bill about STMetrics code.

**Comment by HughCraig** [comment]
Integration of STMetrics is one of the named components of the GHAP as Infrastructure project so this can be Priority 1 for that project.

**Comment by IanMcCrabb** [comment]
This is scheduled for a later phase in the project

**Comment by IanMcCrabb** [comment]
Refer #194
