### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#402]
@MufengNiu  can you remove the following from the test user table as I'd like to do some testing of the registration process 

ianmcccrabb@systemiksolutions.com
iml@systemiksolutions.com
ian@prakas.org

@HughCraig can I also get Mufeng to remove your login from the test db so that you might test registration from a University account

**Comment by MufengNiu** [comment]
@IanMcCrabb 
Removed

**Comment by HughCraig** [comment]
Yes, by all means remove my login and I will try to register anew with my UON address.

**Comment by MufengNiu** [comment]
@HughCraig 
Removed

**Comment by HughCraig** [comment]
Just registered on the test version with my UON email, all good.
