### ISSUE TITLE
Env vars as config

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#42]
This is a refactoring issue to do it the 'right' way. Check this is still best practice. This issue was from someone else and I haven't checked it.

In production, use of the laravel function
env('VAR_NAME', 'Some Default value'),
to access items in the .env file is improper use, and likely to fail.

Instead a config file (myconfig.php) should set variables like so'name' => env('VAR_NAME', 'Some Default value')
and these config variables can then be accessed via config('myconfig.VAR_NAME')

https://stackoverflow.com/questions/40026893/what-is-difference-between-use-envapp-env-configapp-env-or-appenviron/42393294#42393294

**Comment by IanMcCrabb** [comment]
@yangli0516 has this been substantially addressed in the refactoring work?

**Comment by IanMcCrabb** [comment]
Assigned to Hugh to confirm priority for maintenance budget

**Comment by HughCraig** [comment]
Probably taken care of already but it would be good to check.

**Comment by yangli0516** [comment]
Test site updated.
