### ISSUE TITLE
Parse Large Text Fails

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#439]
A very short text works ok, but it looks like a long one does not.
Uploaded Petrie's Reminiscences and tried to parse, but got an error message after a short wait (maybe about 30 seconds):
`{"error":"Failed to send request","details":"Server error: `POST https:\/\/geoparsing.textmap.tlcmap.org\/api\/geoparse` resulted in a `500 Internal Server Error` response:\n<html>\n  <head>\n    <title>Internal Server Error<\/title>\n  <\/head>\n  <body>\n    <h1><p>Internal Server Error<\/p><\/h1>\n   (truncated...)\n"}`
Using Dictionary mode, uploading a file containing only 3 places, one on each line, also failed.
Files used are:
[dictionarytest.txt](https://github.com/user-attachments/files/17830120/dictionarytest.txt)
[testsmalltext.txt](https://github.com/user-attachments/files/17830121/testsmalltext.txt)
[PetriesReminiscences.txt](https://github.com/user-attachments/files/17830132/PetriesReminiscences.txt)

**Comment by isobel-andrews** [comment]
- Change dictionary file upload to 'Choose .csv file' and disallow non-csv files

**Comment by MufengNiu** [comment]
show geocoding places after 'geoparsing'

**Comment by BillPascoe** [comment]
If I start the process for a large text and have ticked to Save places in text to layer automatically' and then navigate away and come back to the 'text', it doesn't give any indication that the text is being processed. I might start a new parse, thinking it had failed. If a text is still processing, add a message to the text page that says, 'Processing' highlighted yellow, and grey out and disable the 'Parse Text' and 'Create Layer From Text' buttons.

**Comment by BillPascoe** [comment]
Dictionaries as CSV work ok.
