### ISSUE TITLE
Review Line and Polygon handling

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#44]
Include checking if upload polygon is converted to point, and consider whether we should handle line and polygon datasets. How does that affect search? Maybe we do store the line/polygon in a single field (comma separated coordinates, following conventions etc) and we also store a point, and we get around the massive confusing mess of searching within, around, intersecting, containing, overlapping polygons and lines by simply searching the point centroid. Not the best but might get us out of the woods. Ie: convert to centroid point on upload and store that in the normal place and have another field (or table depending on if PostGIS has cool features for this) for the line/polygon.

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget

**Comment by BillPascoe** [comment]
Figured it out, updating another issue to do this.
