### ISSUE TITLE
No Text View for Text In Public Page of Layer

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#440]
I parsed and created a layer ok and it looks great. 
But if I go to the layer in the public interface, there is no 'Text' option to View Layer. This should be an option for any parsed Text layer. 
I now reaslise we will need two 'types' for 'Text':
i) 'Text' (for a layer that someone has simply labelled 'text' because they have created places that are related to a text, eg: I do not parse a Shakespeare play, but just have made my own list of places in Shakespeare play and map them) and
ii) 'Full Text' for layers that have been parsed in TLCMap and can be viewed as map + full text in the viewer. If the layer is a 'Full Text' layer, then add 'Full Text' as an option to 'View Map' button, and link to the text-map viewer.
Example layer: https://test-ghap.tlcmap.org/layers/1397

**Comment by MufengNiu** [comment]
provide textmap view for layers can have been made public, hide edit mode button in textmap if open from public layer page.
