### ISSUE TITLE
Clarification on Options

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#441]
This is just to get clarification on why these options for Texts have these choices, and if we can change them:
1. There is an option field for 'Text Type'. Are these relevant to system functioning, or can we just label them what we want? If we can decide what the options are, we might want different ones like 'Fiction, Non-fiction'. We probably don't want to get too complicated.
2. 'Geocoding Bias' has two options (Australia and USA). Can we have more? Can we have global? Can we have a list of countries with Australia selected by default?

**Comment by IanMcCrabb** [comment]
@MufengNiu I think we decide to move ahead on implementing the Geocoding bias options (Yang advised what they should be) and  then pass the issue back to Bill to specify at a set of Text Types

**Comment by BillPascoe** [comment]
The 'text type' options can be:
- Fiction
- Fiction (collection)
- Non-fiction
- Non-fiction (collection)
- Other
The geocoding bias options should be the list of countries from the early version of Text Map, plus an option for 'Global' (or no bias), and Australia should be selected by default.

**Comment by IanMcCrabb** [comment]
@MufengNiu  seems like a very quick enhancement

**Comment by IanMcCrabb** [comment]
@MufengNiu  In the new year
