### ISSUE TITLE
Linking a place to a text

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/GHAP#445]
When I go to add a place to a text in the edit mode in TextMap and add lat and long coordinates manually, a new datapoint appears on the map when I save but there is no modification to the text (I was expecting the word in the text to be given an orange highlight). On the other hand if I select the relevant word in the text and click on the newly created place in the map to auto-populate lat and long, and save, I do get the word highlighted in orange.

**Comment by IanMcCrabb** [comment]
@isobel-andrews can i get you to review before Mufeng makes the change
