### ISSUE TITLE
Places in new text layer not found in search

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#448]
I used Text Map to create a layer called 'Test Text A':
Test Text A
https://test-ghap.tlcmap.org/layers/1404
and it is public. However places in this layer are not being found by Search. Eg: if I search for 'Hall St' or 'Marakesh' these places in the layer are not found.

**Comment by MufengNiu** [comment]
Hi @BillPascoe,

Currently, on the homepage, we are displaying places from three sources: ANPS, NCG, and user-contributed layers. We’ve decided to categorize the places generated by text as a new data source, "Geocoder." As a result, they are not shown under the search.

Should we add a new checkbox labeled "Geocoder" on the homepage, or include them under the user-contributed layers?

**Comment by MufengNiu** [comment]
include in layers

**Comment by BillPascoe** [comment]
Text places now found in search.
