### ISSUE TITLE
Search by keyword / tag

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#46]
The point of the keyword is so people can search/filter topics they are interested in, so make it an option under 'Advanced Search'. Maybe user types in the box and the options filter down as user continues typing - common behaviour for tag/keyword input.

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget

**Comment by BillPascoe** [comment]
Also search within description and extended data as options in advanced search.

**Comment by MufengNiu** [comment]
@BillPascoe . Can you please clarify whether you are referring search for a feature term?

**Comment by BillPascoe** [comment]
Sorry, I had forgotten that the 'keyword' or 'subject' is only in the layer metadata, not the individual places. So this now is just part of the issue to create a 'search layer' feature: https://github.com/HughCraig/GHAP/issues/260 so you can probably just close this one.
