### ISSUE TITLE
URLs to say 'layer' instead of 'dataset'

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#52]
Change URLs that say 'datasets' or 'dataset' to say 'layers' or 'layer' instead. Make backward compatible by leaving the 'dataset' routes as aliases in the routes file.

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget

**Comment by IanMcCrabb** [comment]
Address this as part of API remediation

**Comment by BillPascoe** [comment]
replaced by newly created issue
