### ISSUE TITLE
Map Display - Chrome

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/GHAP#57]
This is a TLCMap issue – maps do not display – specific to Chrome. Possibly associated with a new version of Chrome. Chad’s video records his attempts. As he says in one of the emails TLCMap works fine in Edge on his machine.
Best wishes, 
Hugh.

From: Chad Bennett <[chad.bennett@newcastle.edu.au](mailto:chad.bennett@newcastle.edu.au)> 
Sent: Friday, 5 August 2022 1:37 PM
To: Hugh Craig <[hugh.craig@newcastle.edu.au](mailto:hugh.craig@newcastle.edu.au)>
Subject: RE: Blank screen

Dear Hugh,

Yes, no problem at all – the Systemik people should be able to view the video at this link via Google Drive:

https://drive.google.com/file/d/1CcsmIiKXzMw24brVmgpOnFO5PjQ4vm3Q/view?usp=sharing

**Comment by IanMcCrabb** [comment]
Hugh let me know about the blank screen problem with TLCMap. It's difficult to see what the problem is because I have the same version of Chrome on Windows and it is working ok. If you haven't already please try the following:
1.	Hard refresh the page the map is supposed to appear on (Hold down Ctrl and click the Reload button)
2.	Check if there are any error messages: 
a.	On the map page, right click on the box with the TLCMap log in it
b.	choose 'inspect'
c.	click the 'console' tab
d.	are there any messages in red or yellow?
Try the solutions shown on this page for Chrome: https://doc.arcgis.com/en/arcgis-online/reference/scene-viewer-requirements.htm
We would be very interested to know if any of these are what fix the problem as it may be effecting others

**Comment by HughCraig** [comment]
I have just asked Chad to check if this unexpected behaviour is still happening, as part of our review of longstanding issues labelled "bug".

**Comment by HughCraig** [comment]
Chad reported all was well using Chrome on his machine.
