### ISSUE TITLE
Filter by Layer Type

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#63]
When user creates a layer they can flag it's 'record type' as 'placename', 'site', 'journey', etc. Any other user should be able to filter the search using this under the 'Advanced Search' options. This must be added to the WS API options.

**Comment by IanMcCrabb** [comment]
We can look at this when we get to the 'Enhance GHAP API' phase

**Comment by HughCraig** [comment]
Yes, one use case would be where a user wants to search only for mentions of a place specifically as a place name, and to filter out all the mentions as events etc. This would align well with the narrower definition of what a gazetteer is, i.e. a list of place names with geolocations.

**Comment by MufengNiu** [comment]
The requirement is to search on type pf places instead of layers

**Comment by HughCraig** [comment]
Yes. This would make use of the "Record type" field which users are prompted to fill in (by choosing a term from a dropdown list) when they create a new layer. The new feature would be the ability when doing an Advanced Search to search only those layers which have been designated as one or other Record Type.

**Comment by IanMcCrabb** [comment]
Albeit the outcome might be much the same if places are inheriting the type of the layer, we interpreted this a little differently.  Places have a type and seems like a Layer could contain Places of different types.  So we would actually be searching for all Places of a particular type.

**Comment by HughCraig** [comment]
Yes, good point, places could be of various types within a layer. But the only way I know of that we currently have to assign a type to a place is via the record type -- other than an ad hoc column in a spreadsheet -- is the dropdown on the creating a layer page. So this seems a good place to start, at least.

**Comment by yangli0516** [comment]
Test site has been updated.
