### ISSUE TITLE
URLs listed in user management are not correct

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/GHAP#7]
The current blade template uses the path relative to docroot. Should use the function `url()` to wrap the path.

https://github.com/HughCraig/TLCMap/blob/8ee92eb40765978943a401defc6ba863496270de/ghapapp/resources/views/admin/usermanagement.blade.php#L29-L30

**Comment by BillPascoe** [comment]
If I go to https://test.tlcmap.org/ghap/admin I get 'Error 403 - Forbidden.'

**Comment by yangli0516** [comment]
@BillPascoe could you let me know which account you are using? I can see those two accounts you have are all regular users.

**Comment by BillPascoe** [comment]
Hi Yang,

I log in as:
***@***.***
I checked on the live database and it looked like I was user 5, which has
role 3 which is super user. I can't see any info in the user table but I
figured it out from the userid connected to the layers that I own.

Maybe I'm just confused?

Also btw, if I connect to the test_tlcmap or test_gazetteer database, I
can't see the tables. Should I connect as a different user? Here is what I
see:

postgres=# \c test_tlcmap
You are now connected to database "test_tlcmap" as user "postgres".
test_tlcmap=# \dt
              List of relations
 Schema |      Name       | Type  |  Owner
--------+-----------------+-------+----------
 public | spatial_ref_sys | table | systemik
(1 row)

Kind regards,
Bill Pascoe

**Comment by yangli0516** [comment]
User 5 is ben. I can see user 2 is 'bill.pascoe[At]newcastle.edu.au' and user 4 is 'bpasco2[At]gmail.com'. The email address you commented above is trimmed by GitHub.

I might investigate the database connection later as I thought user 'postgres' is the super user and should have all database access.

**Comment by BillPascoe** [comment]
Yes leave it till tomorrow. I'm user 2 then.

**Comment by yangli0516** [comment]
I've change user 2 to super admin. You should be able to see the admin menu now.

**Comment by BillPascoe** [comment]
Thanks I can see it now.
