### ISSUE TITLE
Check Spam Folder in alerts

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#9]
Any alert/notification related to things that will be emailed, such as account creation or password change, should advise user: "Message sent. If you do not see the message, please check your 'spam', 'junk' or 'deleted' folder. If you did not receive the message, try adding access@tlcmap.org to your email 'white list'. If you still do not get the message please contact tlcmap@newcastle.edu.au"
Eg: password reset gives this message on the screen, but should advise the above:
"We have e-mailed your password reset link!"

**Comment by HughCraig** [comment]
This is a common problem -- the reminder goes to spam so the user thinks the platform has failed to send a message.

**Comment by yangli0516** [comment]
Test site updated.
