### ISSUE TITLE
Garbage GET params in generated URLs

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#95]
Sometimes a 'token' is added to the search parameter, but it seems to work fine without it. Not sure why this was added and if it's necessary. I think it was to do with leaflet a long time ago, which we no longer use. I think we can remove it. There also seems to be other GET query parameters needlessly added in various scenarios. So check and fix all the handling of get query string parameters generated by searches and by user selecting output format options after the search. And in the URLs fed to the views.

Eg: if you do a search then choose to view in GeoJSON, the URL becomes this:
https://tlcmap.org/ghap/search?_token=OsAxAh66BddsiSfn9YM8JVDobbEMT0nf6Oh66DpK&containsnames=&fuzzyname=coo&fuzzynames=&leaflet-base-layers_49=on&names=&searchausgaz=on&searchpublicdatasets=on&format=json

Another EG is if you simply search 'Springfield'

If I simply search for 'Springfield' exact match, the URL is:
https://tlcmap.org/ghap/search?name=Springfield&searchausgaz=on&_token=OsAxAh66BddsiSfn9YM8JVDobbEMT0nf6Oh66DpK&leaflet-base-layers_49=on&names=&fuzzynames=&containsnames=
But this works:
https://tlcmap.org/ghap/search?name=Springfield&searchausgaz=on
So it doesn't need any of these parameters: 
&_token=OsAxAh66BddsiSfn9YM8JVDobbEMT0nf6Oh66DpK&leaflet-base-layers_49=on&names=&fuzzynames=&containsnames=

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget

**Comment by yangli0516** [comment]
The reason of these parameters is that the search form is submitted via 'GET' requests. Therefore, the result page will have all form fields with values as parameters in the URL. For the moment, I can't think of a quick solution to consolidate these parameters in the URL. One way is to use the form action handler only for data validation and consolidation, then forward/redirect to another page used for results displaying. We might leave this to a later phase when we have a little bit more thinking.

The '_token' parameter is generated by CSRF token hidden field within the form. As I can see currently it's only used by the bulk search file upload via AJAX, I moved this field outside the form to prevent it displaying in the URL.

**Comment by BillPascoe** [comment]
The result page should have all form fields with values as parameters in the URL. This is important so user can easily just cut and paste url to share it, and also to pass it to the views. The problem is that it seems like some are added that don't need to be there because user has not selected option. Some 'keys' in the key value pairs in the GET string are empty. They just need to be more tidy. Ie: only add key value pair to the URL GET params if user has put in a value for it.

**Comment by BillPascoe** [comment]
It looks like this is all fixed, except the URL still has 'leaflet-base-layers_49=on'. Check if the code needs this at all. I don't think so as we aren't using Leaflet. So remove it if not.

**Comment by yangli0516** [comment]
The leaflet map is used for the area drawing. You see the leaflet parameters in the URL because the map itself contains some HTML controls such as the map style checkboxes. This will probably get addressed when we do the GHAP site redesign. So this won't be addressed for the moment.

**Comment by yangli0516** [comment]
The leaflet parameter should be solved by the new home page design.

**Comment by HughCraig** [comment]
On testing URLs now look tidy and further solution on the way with new home page design so will close this.
