### ISSUE TITLE
Errors reported in Werekata.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/GHAP#98]
Werekata view of https://test.tlcmap.org/view/collection-werekata.html?sort=start&load=https://test.tlcmap.org/ghap/publiccollections/3/json
has errors for the "I've been everywhere" layer and the "NT Stockroutes" layer. The good thing is that it reports the error in the interface and the console. The error is:
message: "geometryType not set and couldn't be inferred from the provided features"
name: "geojson-layer:missing-property
This seems to indicate an issue in our formating of the geojson structure.
(Or perhaps this is an expected error because the layers don't have dates or something???)

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget
